Schema

 - Matches:
     - MatchId: int
         - MatchWeek: int
         - HomeTeam: int
         - AwayTeam: int
         - MatchResult: pt.MatchResult
         - ThreadUrl: str
         - MatchTime: datetime (convert to UTC?)

 - Standings:
     - MatchId: int
         - UserName: str
             - Points: int

 - Predictions:
     - MatchId: int
         - UserName: str
             - Comment: str
             - CommentTime: datetime (convert to UTC?)


What if someone posts two comments?

{
    "MatchId": {
        "0": {
            "MatchWeek": 0,
            "HomeTeam": "Southampton",
            "
        }
    }
}

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from pathlib import Path
import pandas as pd
from icecream import ic

import predthread as pt
from predthread import fbref

from collections import defaultdict
from copy import deepcopy

In [3]:
root = Path(".").absolute()
print(root)

/Users/julianirwin/Projects/predthread/examples/southamton_24-25_33c895d4

In [4]:
club_names = pt.club_names(root)
api_keys = pt.api_keys(root)
match_metadata = pt.match_metadata(root, match_id=0)
matches_metadata = pt.matches_metadata(root)
matches_metadata_df = pt.matches_metadata_df(root)

# ic(club_names)
# ic(match_metadata)
# ic(matches_metadata)

In [8]:
# Of last completed match
match_id = 10

In [6]:
# Using matchweek, not match id
# i_matchweek = 14
# ic(fbref.match_metadata(i_matchweek=i_matchweek))
# pt.append_match_metadata(root, fbref.match_metadata(i_matchweek))

In [9]:
pd.set_option("display.max_rows", None)
ps = pt.download_predictions(root, match_id)
ps.sort_values(["PredictedHomeGoals", "PredictedAwayGoals"], ascending=False)
# ps

,Comment,PredictedHomeGoals,PredictedAwayGoals
UserName,,,
Antidote-Killer,5-6 thriller,5,6
BanjoPants74,Wolves 4 \nSaints 1,4,1
HelpfulSloth14,3-2,3,2
kempston_joystick,"3-2, horrible match winner in stoppage time.",3,2
Tutush,3-1,3,1
MrJoshua_182,3 - 1 Russell on thin ice.,3,1
Potato271,3-1 An early goal gives us hope that our form ...,3,1
InfernoTurnip,3 - 1\n\nLarsen and Cunha both in the goals. M...,3,1
tugboet,3-0 back to the bottom,3,0
thinlike_napkins,3-0,3,0
meteoritee,3-0,3,0
strider_tom,3-0,3,0
FitzRoyced,2-4\n\nI believe,2,4
madshjort,2-3 hilarious,2,3
redditbanana42,2-3,2,3
ThatMoodyBstard,2-2,2,2
jjbc56,2-2,2,2
NorwegianSaint,2-2,2,2
Jpwf,2-2,2,2
Zapdosman,2-1,2,1
pishkabob,2-1,2,1
Nas1729,2-1,2,1
Positive-Sound-4972,2-1 reality strikes,2,1
specifylength,2-1,2,1
TheFuzzyEucalyptus,2-1,2,1
saintstu,2-1 Can’t see wolves not winning this,2,1
NagromNitsuj,2-1 defeat.,2,1
chebalebs,2-1 \nPredicting us to lose last week worked,2,1
uuuuuuuhhhhh,"2-1 we score first half, r/championship style ...",2,1
LegitimatePass6924,2-1😐,2,1
Lost_Disk,2-1,2,1
BFT_022,2-1,2,1
nape27,2-1,2,1
flailingpariah,2-0 sadness,2,0
Cervix-Pounder,2 - 0,2,0
Geralt0908,2-0,2,0
craig_hoxton,2-0,2,0
JAChambel,2-0,2,0
teuridge,2-0,2,0
dan_3,1-3,1,3
RevengeofSudz,Fuck it\n\nWolves 1 - 3 Saints,1,3
whowantstogo,1-3 let's go,1,3
zoinks10,1-3 I’m optimistic because I’m stupid.,1,3
aredditusername69,1-3,1,3
darave123,1-3 mon saints!,1,3
BJH19,1-3,1,3
gubbyno,"1-3, they are rubbish at defending",1,3
benscott81,1-3 feeling optimistic/suffering from delusion.,1,3
istarisaints,1-2,1,2
Bruceplanet,1-2 we snatch it at the death but it's scrappy.,1,2
shontgomery,1-2 we roll on!,1,2
MerryRain,"winnable, 1-2",1,2
Tough-Whereas1205,1-2,1,2
kyleandrew_7,1-2,1,2
DeadSpaceLover,1 - 2 Saints Win,1,2
CelaenaSardothien007,1-2,1,2
FalafelHalloumi,1-2,1,2
Weary_Initiative5582,1-2,1,2
cameronastonmartin,1-2 big Paul header with 5 mins to go,1,2
Desperate_Low9482,1-2,1,2
Intermittent-Thinker,1-2,1,2
Tspecs05,1-2. Gotta keep believing and continue our mom...,1,2
fartarus,1-2,1,2
Nixstricks,1-1 Disappointing but not terrible,1,1
lemezier,1-1,1,1
MetaRift,1-1,1,1
malkusm,1-1,1,1
spankeycakes,1-1,1,1
BlameTibor,1-1 they score from a schoolboy error,1,1
Hefty-Competition297,1-1 COYR,1,1
Kindlydestroyed,"1-1\nA result that in all reality, does not he...",1,1
Saint_Noog,"1-1 not good, not bad",1,1
infestationE15,1-1. I said Martin would need 4 points from Wo...,1,1
gradi3nt,1-0 devastating,1,0
UtterlyRedditculous,1-0,1,0
halarhala,1-0,1,0
GraveRaven,1-0. We always drop the ball against Wolves.,1,0
Hot_Chair_7523,1-0,1,0
rndltr,0-6 we batter them (I dreamt it),0,6
master_shifwho,0-3,0,3
wostmardin,0-2,0,2
pctomfor,0-2,0,2
Boring_Inflation1494,0-2.,0,2
Grumblepiglet,0-2 Saints! Never in doubt!,0,2
J_Dymond,0-2 saints,0,2
oldredstang66,0-1 tight win just,0,1
who905,0-1,0,1
JimmyRiddle707,0-1,0,1
mcsgwigga,0-1,0,1
496e636f676e69746f,0-1,0,1
thatcrazyhorse,0-1,0,1
FleetCasual,A tense but boring 0-0 that does nothing for e...,0,0

In [10]:
pt.summarize_predictions(root, match_id)

{'TotalPredictions': 92,
 'TotalHomeWinPredictions': 36,
 'TotalAwayWinPredictions': 41,
 'TotalDrawPredictions': 15}

In [11]:
new_standings = pt.calculate_updated_standings_after(root, match_id)
new_standings

,Points,PointsGained,Streak,Exacts,Corrects,Wrongs,MaxStreak
UserName,,,,,,,
flailingpariah,13,3,3,2,7,2,6
halarhala,13,1,8,2,7,1,8
slugmaniac,13,0,4,3,4,3,4
Nixstricks,13,0,0,3,4,4,7
LegitimatePass6924,12,1,1,2,6,3,6
Saint_Noog,12,0,0,2,6,2,11
teuridge,10,3,3,1,7,3,4
Nas1729,10,1,5,1,7,2,5
Zapdosman,10,1,1,1,7,3,5
malkusm,10,0,0,2,4,5,8
Intermittent-Thinker,10,0,0,1,7,3,7
specifylength,9,1,8,1,6,3,8
NagromNitsuj,9,1,3,1,6,2,5
gradi3nt,9,1,1,0,9,2,4
HandsomedanNZ,9,0,7,1,6,3,7
jjbc56,9,0,0,1,6,3,8
JAChambel,8,3,3,1,5,2,3
pishkabob,8,1,5,0,8,3,5
shontgomery,8,0,0,2,2,5,3
MetaRift,8,0,0,1,5,5,6
lemezier,8,0,0,1,5,5,3
Emergency-Room-5484,8,0,0,0,8,2,4
Cervix-Pounder,7,3,3,1,4,2,3
chebalebs,7,1,1,1,4,4,3
uuuuuuuhhhhh,7,1,3,0,7,4,3
TheFuzzyEucalyptus,7,1,1,0,7,2,3
UtterlyRedditculous,7,1,1,0,7,2,4
strider_tom,7,1,1,0,7,4,4
magneticacorn,7,0,4,1,4,5,4
FalafelHalloumi,7,0,0,1,4,6,3
benscott81,7,0,0,1,4,5,3
Jpwf,7,0,0,1,4,5,3
ThatMoodyBstard,7,0,0,0,7,3,4
Zou-KaiLi,7,0,0,0,7,3,4
Hot_Chair_7523,6,1,1,1,3,6,3
meteoritee,6,1,6,0,6,0,6
thinlike_napkins,6,1,1,0,6,2,3
nape27,6,1,1,0,6,5,2
fcf4,6,0,5,1,3,1,5
redditbanana42,6,0,0,1,3,7,3
fartarus,6,0,0,0,6,5,2
Boring_Inflation1494,6,0,0,0,6,2,5
craig_hoxton,5,3,5,1,2,0,5
BFT_022,5,1,1,0,5,1,4
lakermamba1999,5,0,1,1,2,1,4
mcsgwigga,5,0,0,0,5,6,3
infestationE15,5,0,0,0,5,5,2
Geralt0908,4,3,3,1,1,2,3
GraveRaven,4,1,4,0,4,0,4
HelpfulSloth14,4,1,4,0,4,0,4
Tutush,4,1,3,0,4,1,3
Potato271,4,1,1,0,4,5,2
MrJoshua_182,4,1,1,0,4,4,1
Positive-Sound-4972,4,1,1,0,4,4,1
tugboet,4,1,1,0,4,5,2
saintstu,4,1,1,0,4,7,1
KanetsuguNaoe,4,0,4,1,1,1,4
JoshHQ,4,0,4,1,1,0,4
PM_ME_YOUR_MARS_BARS,4,0,0,1,1,2,4
kyleandrew_7,4,0,0,1,1,5,3
rapsin4lmao,4,0,0,1,1,1,4
brandonouthouse,4,0,0,1,1,4,3
hAkonf,4,0,2,0,4,2,2
saint-86,4,0,1,0,4,2,2
FitzRoyced,4,0,0,0,4,3,2
Kindlydestroyed,4,0,0,0,4,2,2
JimmyRiddle707,4,0,0,0,4,6,1
CelaenaSardothien007,4,0,0,0,4,4,2
Tough-Whereas1205,4,0,0,0,4,5,2
zoinks10,4,0,0,0,4,6,2
who905,4,0,0,0,4,5,2
StreetSuspicious8456,3,0,3,1,0,0,3
HOWDY__YALL,3,0,3,1,0,0,3
TheTyrantis,3,0,3,1,0,0,3
Deadpooldan,3,0,3,1,0,0,3
SomeGuyCalledPercy,3,0,0,1,0,1,3
uKrayZ,3,0,0,1,0,1,3
3ch03d,3,0,3,0,3,2,3
Revolutionary_Cup602,3,0,2,0,3,1,2
delegod1,3,0,2,0,3,3,2
mdubyo,3,0,2,0,3,2,2
RuleBritannia1919,3,0,1,0,3,1,2
hahs95,3,0,1,0,3,1,2
MangerDanger1,3,0,1,0,3,4,1
Relevant_Rev,3,0,1,0,3,6,1
jackodriscol,3,0,0,0,3,2,3
dan_3,3,0,0,0,3,7,1
NorwegianSaint,3,0,0,0,3,4,2
thatcrazyhorse,3,0,0,0,3,4,1
Bruceplanet,3,0,0,0,3,7,1
oldredstang66,3,0,0,0,3,6,2
kempston_joystick,2,1,2,0,2,2,2
Lost_Disk,2,1,2,0,2,3,2
BanjoPants74,2,1,1,0,2,1,1
Zstupple,2,0,2,0,2,0,2
LovingCatholicPriest,2,0,2,0,2,1,2
Anglo-fornian,2,0,2,0,2,2,2
Likunandi,2,0,2,0,2,0,2
Opposite_Sir1549,2,0,2,0,2,0,2
Many_Background_3679,2,0,1,0,2,2,1
Lucky_Strike1,2,0,1,0,2,5,1
GordonRamsayGhost,2,0,1,0,2,1,1
PhilipRobertson,2,0,1,0,2,2,1
GuteLord-,2,0,1,0,2,2,1
LordOrtus,2,0,1,0,2,3,1
Bayne7096,2,0,1,0,2,3,1
gedly89,2,0,1,0,2,4,1
jeromereyes,2,0,1,0,2,1,1
Weirdo_boy02,2,0,1,0,2,3,1
jayforplay,2,0,0,0,2,2,1
accidentalsalmon,2,0,0,0,2,2,2
Klutzy-Put-1786,2,0,0,0,2,2,1
spankeycakes,2,0,0,0,2,6,1
BlameTibor,2,0,0,0,2,2,2
bendezhashein,2,0,0,0,2,1,2
Desperate_Low9482,2,0,0,0,2,5,1
Tspecs05,2,0,0,0,2,7,2
DeadSpaceLover,2,0,0,0,2,3,1
aredditusername69,2,0,0,0,2,4,1
Weary_Initiative5582,2,0,0,0,2,4,2
InfernoTurnip,1,1,1,0,1,0,1
igsey,1,0,1,0,1,0,1
FluidSaint,1,0,1,0,1,0,1
T_Hr0,1,0,1,0,1,0,1
Finoptics,1,0,1,0,1,0,1
mr_grission,1,0,1,0,1,0,1
KingHarpoon616,1,0,1,0,1,0,1
chesterchugger,1,0,1,0,1,0,1
3rd__i,1,0,1,0,1,3,1
baristaboy24,1,0,1,0,1,1,1
bathtub_not_beach,1,0,1,0,1,1,1
Fast-Engineer915,1,0,1,0,1,1,1
Zakedawn,1,0,1,0,1,0,1
buddyomg,1,0,1,0,1,0,1
Wafflz__,1,0,1,0,1,0,1
BevvyTime,1,0,1,0,1,0,1
galaxygalaxy777,1,0,1,0,1,0,1
Squm9,1,0,1,0,1,1,1
Captain_Obvious_x,1,0,1,0,1,1,1
Fatty4forks,1,0,1,0,1,0,1
exhaleair,1,0,1,0,1,3,1
rabbitradar,1,0,1,0,1,2,1
TouristDramatic8295,1,0,1,0,1,1,1
kevmccartney,1,0,1,0,1,1,1
SoggyMattress2,1,0,1,0,1,0,1
boondocksaint08,1,0,1,0,1,0,1
OpScreechingHalt,1,0,1,0,1,0,1
Educational_Ad288,1,0,1,0,1,0,1
No_Amphibian6382,1,0,1,0,1,0,1
ThermoWizz,1,0,1,0,1,0,1
GuyInWessex,1,0,1,0,1,0,1
Patentlyy,1,0,1,0,1,1,1
JoeGordon07,1,0,1,0,1,1,1
fanea1,1,0,1,0,1,0,1
Scared_Leading2875,1,0,1,0,1,0,1
whattodotodo8,1,0,1,0,1,8,1
Suspicious-Living683,1,0,1,0,1,0,1
ShadowedEclipse,1,0,1,0,1,0,1
Salt-Cup-2300,1,0,0,0,1,3,1
Blackgotham-12,1,0,0,0,1,2,1
Toast_for_President,1,0,0,0,1,1,1
asdaf22,1,0,0,0,1,1,1
Adziboy,1,0,0,0,1,1,1
Henghast,1,0,0,0,1,1,1
rghsfc,1,0,0,0,1,4,1
fluffyplayery,1,0,0,0,1,1,1
Ahegaopizza,1,0,0,0,1,2,1
thisisclassicus,1,0,0,0,1,2,1
J_Dymond,1,0,0,0,1,4,1
madshjort,1,0,0,0,1,5,1
allbarneynorubble,1,0,0,0,1,3,1
BJH19,1,0,0,0,1,5,1
496e636f676e69746f,1,0,0,0,1,7,1
Holy_Shit_Balls_69,1,0,0,0,1,5,1
TrumpsCheetoJizz,1,0,0,0,1,1,1
Beardedmetalhead,1,0,0,0,1,1,1
Financial-Glass5693,1,0,0,0,1,2,1
LukeBron,1,0,0,0,1,1,1
parabola9999,1,0,0,0,1,1,1
wostmardin,1,0,0,0,1,4,1
gubbyno,1,0,0,0,1,4,1
Antidote-Killer,1,0,0,0,1,7,1
whowantstogo,1,0,0,0,1,9,1
Hefty-Competition297,1,0,0,0,1,10,1
master_shifwho,1,0,0,0,1,4,1
alki07,0,0,0,0,0,1,0
MAFIAxMaverick,0,0,0,0,0,4,0
gooffking,0,0,0,0,0,2,0
roberthart327,0,0,0,0,0,1,0
darave123,0,0,0,0,0,4,0
Unlucky_Island_742,0,0,0,0,0,2,0
Vsovs,0,0,0,0,0,1,0
WaltertheWobot,0,0,0,0,0,2,0
happysnappygoat,0,0,0,0,0,1,0
frooberts,0,0,0,0,0,1,0
K3GGY,0,0,0,0,0,1,0
Dr-Honks,0,0,0,0,0,2,0
EntersMikers,0,0,0,0,0,1,0
MrRyan1320,0,0,0,0,0,2,0
sgm94,0,0,0,0,0,3,0
guillotine-jones,0,0,0,0,0,2,0
Super-saints12,0,0,0,0,0,1,0
GrandmasterYoda1,0,0,0,0,0,2,0
TheEggMan45,0,0,0,0,0,1,0
gongasf,0,0,0,0,0,2,0
pctomfor,0,0,0,0,0,3,0
jrdn1616,0,0,0,0,0,2,0
BlueInq,0,0,0,0,0,2,0
bundy554,0,0,0,0,0,1,0
Whenthebeatdropolis,0,0,0,0,0,1,0
street--donut,0,0,0,0,0,1,0
Glittering-Cow-4702,0,0,0,0,0,1,0
DrShaftmanPhD,0,0,0,0,0,3,0
Potential-Oil-1795,0,0,0,0,0,1,0
soverign_cheese,0,0,0,0,0,1,0
BigTettenator,0,0,0,0,0,2,0
West_Equivalent7997,0,0,0,0,0,1,0
MonarchyBoner,0,0,0,0,0,1,0
Alina2017,0,0,0,0,0,1,0
Cormac419,0,0,0,0,0,1,0
King_Lamb,0,0,0,0,0,1,0
PunnyIsNotFunny,0,0,0,0,0,1,0
weatherghost,0,0,0,0,0,1,0
Nervous_Jaguar_2826,0,0,0,0,0,1,0
throwaway1throwawa,0,0,0,0,0,2,0
jonnyhoots,0,0,0,0,0,2,0
JoeBiggzDC,0,0,0,0,0,1,0
LiveFree-603,0,0,0,0,0,1,0
TheHatThatTalks,0,0,0,0,0,1,0
Top_Dirt2557,0,0,0,0,0,1,0
Notional-,0,0,0,0,0,1,0
BrandonPol,0,0,0,0,0,1,0
Singh255,0,0,0,0,0,1,0
King_PieNan,0,0,0,0,0,1,0
Ok_Mix_3544,0,0,0,0,0,2,0
matt_rev,0,0,0,0,0,3,0
Mr_Yellow_Trousers,0,0,0,0,0,4,0
Magmar18,0,0,0,0,0,1,0
neil2252,0,0,0,0,0,1,0
No_Wrap_9979,0,0,0,0,0,1,0
istarisaints,0,0,0,0,0,2,0
FromTheEdgeOfTheDeep,0,0,0,0,0,2,0
Jamez_XIX,0,0,0,0,0,1,0
Evening-Tart3067,0,0,0,0,0,1,0
mbridge2610,0,0,0,0,0,1,0
senorbellend17,0,0,0,0,0,1,0
No_Pound5513,0,0,0,0,0,1,0
HorusHeresay,0,0,0,0,0,1,0
GreedoVision,0,0,0,0,0,1,0
TheSpitfires,0,0,0,0,0,1,0
fl0ralp,0,0,0,0,0,2,0
Adventurous_Bass_673,0,0,0,0,0,1,0
YourWeekendDad,0,0,0,0,0,1,0
rigill,0,0,0,0,0,1,0
nmc1995,0,0,0,0,0,1,0
Same-Temporary8468,0,0,0,0,0,1,0
dinzil02,0,0,0,0,0,1,0
Crazymorsejr,0,0,0,0,0,1,0
MerryRain,0,0,0,0,0,2,0
Special_Tune9184,0,0,0,0,0,1,0
slashmpw,0,0,0,0,0,1,0
Harris_vs,0,0,0,0,0,1,0
benjwilliam,0,0,0,0,0,1,0
Stix-Zadupya,0,0,0,0,0,1,0
RevengeofSudz,0,0,0,0,0,1,0
cameronastonmartin,0,0,0,0,0,1,0
Grumblepiglet,0,0,0,0,0,1,0
rndltr,0,0,0,0,0,1,0
FleetCasual,0,0,0,0,0,1,0

In [12]:
print(new_standings.reset_index().to_markdown())

|     | UserName             |   Points |   PointsGained |   Streak |   Exacts |   Corrects |   Wrongs |   MaxStreak |
|----:|:---------------------|---------:|---------------:|---------:|---------:|-----------:|---------:|------------:|
|   0 | flailingpariah       |       13 |              3 |        3 |        2 |          7 |        2 |           6 |
|   1 | halarhala            |       13 |              1 |        8 |        2 |          7 |        1 |           8 |
|   2 | slugmaniac           |       13 |              0 |        4 |        3 |          4 |        3 |           4 |
|   3 | Nixstricks           |       13 |              0 |        0 |        3 |          4 |        4 |           7 |
|   4 | LegitimatePass6924   |       12 |              1 |        1 |        2 |          6 |        3 |           6 |
|   5 | Saint_Noog           |       12 |              0 |        0 |        2 |          6 |        2 |          11 |
|   6 | teuridge             |       10 |              3 |        3 |        1 |          7 |        3 |           4 |
|   7 | Nas1729              |       10 |              1 |        5 |        1 |          7 |        2 |           5 |
|   8 | Zapdosman            |       10 |              1 |        1 |        1 |          7 |        3 |           5 |
|   9 | malkusm              |       10 |              0 |        0 |        2 |          4 |        5 |           8 |
|  10 | Intermittent-Thinker |       10 |              0 |        0 |        1 |          7 |        3 |           7 |
|  11 | specifylength        |        9 |              1 |        8 |        1 |          6 |        3 |           8 |
|  12 | NagromNitsuj         |        9 |              1 |        3 |        1 |          6 |        2 |           5 |
|  13 | gradi3nt             |        9 |              1 |        1 |        0 |          9 |        2 |           4 |
|  14 | HandsomedanNZ        |        9 |              0 |        7 |        1 |          6 |        3 |           7 |
|  15 | jjbc56               |        9 |              0 |        0 |        1 |          6 |        3 |           8 |
|  16 | JAChambel            |        8 |              3 |        3 |        1 |          5 |        2 |           3 |
|  17 | pishkabob            |        8 |              1 |        5 |        0 |          8 |        3 |           5 |
|  18 | shontgomery          |        8 |              0 |        0 |        2 |          2 |        5 |           3 |
|  19 | MetaRift             |        8 |              0 |        0 |        1 |          5 |        5 |           6 |
|  20 | lemezier             |        8 |              0 |        0 |        1 |          5 |        5 |           3 |
|  21 | Emergency-Room-5484  |        8 |              0 |        0 |        0 |          8 |        2 |           4 |
|  22 | Cervix-Pounder       |        7 |              3 |        3 |        1 |          4 |        2 |           3 |
|  23 | chebalebs            |        7 |              1 |        1 |        1 |          4 |        4 |           3 |
|  24 | uuuuuuuhhhhh         |        7 |              1 |        3 |        0 |          7 |        4 |           3 |
|  25 | TheFuzzyEucalyptus   |        7 |              1 |        1 |        0 |          7 |        2 |           3 |
|  26 | UtterlyRedditculous  |        7 |              1 |        1 |        0 |          7 |        2 |           4 |
|  27 | strider_tom          |        7 |              1 |        1 |        0 |          7 |        4 |           4 |
|  28 | magneticacorn        |        7 |              0 |        4 |        1 |          4 |        5 |           4 |
|  29 | FalafelHalloumi      |        7 |              0 |        0 |        1 |          4 |        6 |           3 |
|  30 | benscott81           |        7 |              0 |        0 |        1 |          4 |        5 |           3 |
|  31 | Jpwf                 |        7 |              0 |        0 |        1 |          4 |        5 |           3 |
|  32 | ThatMoodyBstard      |        7 |              0 |        0 |        0 |          7 |        3 |           4 |
|  33 | Zou-KaiLi            |        7 |              0 |        0 |        0 |          7 |        3 |           4 |
|  34 | Hot_Chair_7523       |        6 |              1 |        1 |        1 |          3 |        6 |           3 |
|  35 | meteoritee           |        6 |              1 |        6 |        0 |          6 |        0 |           6 |
|  36 | thinlike_napkins     |        6 |              1 |        1 |        0 |          6 |        2 |           3 |
|  37 | nape27               |        6 |              1 |        1 |        0 |          6 |        5 |           2 |
|  38 | fcf4                 |        6 |              0 |        5 |        1 |          3 |        1 |           5 |
|  39 | redditbanana42       |        6 |              0 |        0 |        1 |          3 |        7 |           3 |
|  40 | fartarus             |        6 |              0 |        0 |        0 |          6 |        5 |           2 |
|  41 | Boring_Inflation1494 |        6 |              0 |        0 |        0 |          6 |        2 |           5 |
|  42 | craig_hoxton         |        5 |              3 |        5 |        1 |          2 |        0 |           5 |
|  43 | BFT_022              |        5 |              1 |        1 |        0 |          5 |        1 |           4 |
|  44 | lakermamba1999       |        5 |              0 |        1 |        1 |          2 |        1 |           4 |
|  45 | mcsgwigga            |        5 |              0 |        0 |        0 |          5 |        6 |           3 |
|  46 | infestationE15       |        5 |              0 |        0 |        0 |          5 |        5 |           2 |
|  47 | Geralt0908           |        4 |              3 |        3 |        1 |          1 |        2 |           3 |
|  48 | GraveRaven           |        4 |              1 |        4 |        0 |          4 |        0 |           4 |
|  49 | HelpfulSloth14       |        4 |              1 |        4 |        0 |          4 |        0 |           4 |
|  50 | Tutush               |        4 |              1 |        3 |        0 |          4 |        1 |           3 |
|  51 | Potato271            |        4 |              1 |        1 |        0 |          4 |        5 |           2 |
|  52 | MrJoshua_182         |        4 |              1 |        1 |        0 |          4 |        4 |           1 |
|  53 | Positive-Sound-4972  |        4 |              1 |        1 |        0 |          4 |        4 |           1 |
|  54 | tugboet              |        4 |              1 |        1 |        0 |          4 |        5 |           2 |
|  55 | saintstu             |        4 |              1 |        1 |        0 |          4 |        7 |           1 |
|  56 | KanetsuguNaoe        |        4 |              0 |        4 |        1 |          1 |        1 |           4 |
|  57 | JoshHQ               |        4 |              0 |        4 |        1 |          1 |        0 |           4 |
|  58 | PM_ME_YOUR_MARS_BARS |        4 |              0 |        0 |        1 |          1 |        2 |           4 |
|  59 | kyleandrew_7         |        4 |              0 |        0 |        1 |          1 |        5 |           3 |
|  60 | rapsin4lmao          |        4 |              0 |        0 |        1 |          1 |        1 |           4 |
|  61 | brandonouthouse      |        4 |              0 |        0 |        1 |          1 |        4 |           3 |
|  62 | hAkonf               |        4 |              0 |        2 |        0 |          4 |        2 |           2 |
|  63 | saint-86             |        4 |              0 |        1 |        0 |          4 |        2 |           2 |
|  64 | FitzRoyced           |        4 |              0 |        0 |        0 |          4 |        3 |           2 |
|  65 | Kindlydestroyed      |        4 |              0 |        0 |        0 |          4 |        2 |           2 |
|  66 | JimmyRiddle707       |        4 |              0 |        0 |        0 |          4 |        6 |           1 |
|  67 | CelaenaSardothien007 |        4 |              0 |        0 |        0 |          4 |        4 |           2 |
|  68 | Tough-Whereas1205    |        4 |              0 |        0 |        0 |          4 |        5 |           2 |
|  69 | zoinks10             |        4 |              0 |        0 |        0 |          4 |        6 |           2 |
|  70 | who905               |        4 |              0 |        0 |        0 |          4 |        5 |           2 |
|  71 | StreetSuspicious8456 |        3 |              0 |        3 |        1 |          0 |        0 |           3 |
|  72 | HOWDY__YALL          |        3 |              0 |        3 |        1 |          0 |        0 |           3 |
|  73 | TheTyrantis          |        3 |              0 |        3 |        1 |          0 |        0 |           3 |
|  74 | Deadpooldan          |        3 |              0 |        3 |        1 |          0 |        0 |           3 |
|  75 | SomeGuyCalledPercy   |        3 |              0 |        0 |        1 |          0 |        1 |           3 |
|  76 | uKrayZ               |        3 |              0 |        0 |        1 |          0 |        1 |           3 |
|  77 | 3ch03d               |        3 |              0 |        3 |        0 |          3 |        2 |           3 |
|  78 | Revolutionary_Cup602 |        3 |              0 |        2 |        0 |          3 |        1 |           2 |
|  79 | delegod1             |        3 |              0 |        2 |        0 |          3 |        3 |           2 |
|  80 | mdubyo               |        3 |              0 |        2 |        0 |          3 |        2 |           2 |
|  81 | RuleBritannia1919    |        3 |              0 |        1 |        0 |          3 |        1 |           2 |
|  82 | hahs95               |        3 |              0 |        1 |        0 |          3 |        1 |           2 |
|  83 | MangerDanger1        |        3 |              0 |        1 |        0 |          3 |        4 |           1 |
|  84 | Relevant_Rev         |        3 |              0 |        1 |        0 |          3 |        6 |           1 |
|  85 | jackodriscol         |        3 |              0 |        0 |        0 |          3 |        2 |           3 |
|  86 | dan_3                |        3 |              0 |        0 |        0 |          3 |        7 |           1 |
|  87 | NorwegianSaint       |        3 |              0 |        0 |        0 |          3 |        4 |           2 |
|  88 | thatcrazyhorse       |        3 |              0 |        0 |        0 |          3 |        4 |           1 |
|  89 | Bruceplanet          |        3 |              0 |        0 |        0 |          3 |        7 |           1 |
|  90 | oldredstang66        |        3 |              0 |        0 |        0 |          3 |        6 |           2 |
|  91 | kempston_joystick    |        2 |              1 |        2 |        0 |          2 |        2 |           2 |
|  92 | Lost_Disk            |        2 |              1 |        2 |        0 |          2 |        3 |           2 |
|  93 | BanjoPants74         |        2 |              1 |        1 |        0 |          2 |        1 |           1 |
|  94 | Zstupple             |        2 |              0 |        2 |        0 |          2 |        0 |           2 |
|  95 | LovingCatholicPriest |        2 |              0 |        2 |        0 |          2 |        1 |           2 |
|  96 | Anglo-fornian        |        2 |              0 |        2 |        0 |          2 |        2 |           2 |
|  97 | Likunandi            |        2 |              0 |        2 |        0 |          2 |        0 |           2 |
|  98 | Opposite_Sir1549     |        2 |              0 |        2 |        0 |          2 |        0 |           2 |
|  99 | Many_Background_3679 |        2 |              0 |        1 |        0 |          2 |        2 |           1 |
| 100 | Lucky_Strike1        |        2 |              0 |        1 |        0 |          2 |        5 |           1 |
| 101 | GordonRamsayGhost    |        2 |              0 |        1 |        0 |          2 |        1 |           1 |
| 102 | PhilipRobertson      |        2 |              0 |        1 |        0 |          2 |        2 |           1 |
| 103 | GuteLord-            |        2 |              0 |        1 |        0 |          2 |        2 |           1 |
| 104 | LordOrtus            |        2 |              0 |        1 |        0 |          2 |        3 |           1 |
| 105 | Bayne7096            |        2 |              0 |        1 |        0 |          2 |        3 |           1 |
| 106 | gedly89              |        2 |              0 |        1 |        0 |          2 |        4 |           1 |
| 107 | jeromereyes          |        2 |              0 |        1 |        0 |          2 |        1 |           1 |
| 108 | Weirdo_boy02         |        2 |              0 |        1 |        0 |          2 |        3 |           1 |
| 109 | jayforplay           |        2 |              0 |        0 |        0 |          2 |        2 |           1 |
| 110 | accidentalsalmon     |        2 |              0 |        0 |        0 |          2 |        2 |           2 |
| 111 | Klutzy-Put-1786      |        2 |              0 |        0 |        0 |          2 |        2 |           1 |
| 112 | spankeycakes         |        2 |              0 |        0 |        0 |          2 |        6 |           1 |
| 113 | BlameTibor           |        2 |              0 |        0 |        0 |          2 |        2 |           2 |
| 114 | bendezhashein        |        2 |              0 |        0 |        0 |          2 |        1 |           2 |
| 115 | Desperate_Low9482    |        2 |              0 |        0 |        0 |          2 |        5 |           1 |
| 116 | Tspecs05             |        2 |              0 |        0 |        0 |          2 |        7 |           2 |
| 117 | DeadSpaceLover       |        2 |              0 |        0 |        0 |          2 |        3 |           1 |
| 118 | aredditusername69    |        2 |              0 |        0 |        0 |          2 |        4 |           1 |
| 119 | Weary_Initiative5582 |        2 |              0 |        0 |        0 |          2 |        4 |           2 |
| 120 | InfernoTurnip        |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
| 121 | igsey                |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 122 | FluidSaint           |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 123 | T_Hr0                |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 124 | Finoptics            |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 125 | mr_grission          |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 126 | KingHarpoon616       |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 127 | chesterchugger       |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 128 | 3rd__i               |        1 |              0 |        1 |        0 |          1 |        3 |           1 |
| 129 | baristaboy24         |        1 |              0 |        1 |        0 |          1 |        1 |           1 |
| 130 | bathtub_not_beach    |        1 |              0 |        1 |        0 |          1 |        1 |           1 |
| 131 | Fast-Engineer915     |        1 |              0 |        1 |        0 |          1 |        1 |           1 |
| 132 | Zakedawn             |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 133 | buddyomg             |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 134 | Wafflz__             |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 135 | BevvyTime            |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 136 | galaxygalaxy777      |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 137 | Squm9                |        1 |              0 |        1 |        0 |          1 |        1 |           1 |
| 138 | Captain_Obvious_x    |        1 |              0 |        1 |        0 |          1 |        1 |           1 |
| 139 | Fatty4forks          |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 140 | exhaleair            |        1 |              0 |        1 |        0 |          1 |        3 |           1 |
| 141 | rabbitradar          |        1 |              0 |        1 |        0 |          1 |        2 |           1 |
| 142 | TouristDramatic8295  |        1 |              0 |        1 |        0 |          1 |        1 |           1 |
| 143 | kevmccartney         |        1 |              0 |        1 |        0 |          1 |        1 |           1 |
| 144 | SoggyMattress2       |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 145 | boondocksaint08      |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 146 | OpScreechingHalt     |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 147 | Educational_Ad288    |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 148 | No_Amphibian6382     |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 149 | ThermoWizz           |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 150 | GuyInWessex          |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 151 | Patentlyy            |        1 |              0 |        1 |        0 |          1 |        1 |           1 |
| 152 | JoeGordon07          |        1 |              0 |        1 |        0 |          1 |        1 |           1 |
| 153 | fanea1               |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 154 | Scared_Leading2875   |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 155 | whattodotodo8        |        1 |              0 |        1 |        0 |          1 |        8 |           1 |
| 156 | Suspicious-Living683 |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 157 | ShadowedEclipse      |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 158 | Salt-Cup-2300        |        1 |              0 |        0 |        0 |          1 |        3 |           1 |
| 159 | Blackgotham-12       |        1 |              0 |        0 |        0 |          1 |        2 |           1 |
| 160 | Toast_for_President  |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
| 161 | asdaf22              |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
| 162 | Adziboy              |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
| 163 | Henghast             |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
| 164 | rghsfc               |        1 |              0 |        0 |        0 |          1 |        4 |           1 |
| 165 | fluffyplayery        |        1 |              0 |        0 |        0 |          1 |        1 |           1 |

In [10]:
predictions = pt.load_predictions(root, match_id)
old_standings = pt.load_standings_after(root, match_id - 1)
new_standings_p = pt.load_standings_after(root, match_id)
new_standings_p = new_standings.rename(columns=lambda x: x + "*")
predictions.join(old_standings, new_standings_p)

KeyError:                       Points*  PointsGained*  Streak*  Exacts*  Corrects*  \
UserName
Nixstricks                 12              1        1        3          3
LegitimatePass6924         11              1        6        2          5
slugmaniac                 10              1        1        2          4
flailingpariah             10              1        4        1          7
Saint_Noog                  9              1        8        1          6
jjbc56                      9              1        8        1          6
halarhala                   9              1        4        1          6
Zapdosman                   9              1        3        1          6
HandsomedanNZ               8              1        6        1          5
MetaRift                    8              1        1        1          5
gradi3nt                    8              1        4        0          8
Emergency-Room-5484         8              1        4        0          8
Nas1729                     8              0        3        1          5
malkusm                     7              1        5        1          4
lemezier                    7              1        1        1          4
NagromNitsuj                7              1        1        1          4
teuridge                    7              1        4        0          7
Zou-KaiLi                   7              1        4        0          7
Intermittent-Thinker        7              1        4        0          7
ThatMoodyBstard             7              1        3        0          7
shontgomery                 7              0        0        2          1
FalafelHalloumi             7              0        0        1          4
chebalebs                   6              1        2        1          3
Jpwf                        6              1        2        1          3
benscott81                  6              1        1        1          3
strider_tom                 6              1        4        0          6
pishkabob                   6              1        3        0          6
UtterlyRedditculous         6              1        2        0          6
fcf4                        6              0        5        1          3
TheFuzzyEucalyptus          6              0        3        0          6
Hot_Chair_7523              5              1        1        1          2
redditbanana42              5              1        1        1          2
meteoritee                  5              1        5        0          5
specifylength               5              1        4        0          5
Boring_Inflation1494        5              1        4        0          5
JAChambel                   5              1        3        0          5
uuuuuuuhhhhh                5              1        1        0          5
fartarus                    5              1        1        0          5
nape27                      5              1        1        0          5
infestationE15              5              1        1        0          5
lakermamba1999              5              0        1        1          2
thinlike_napkins            5              0        2        0          5
mcsgwigga                   5              0        0        0          5
JoshHQ                      4              1        4        1          1
BFT_022                     4              1        4        0          4
hAkonf                      4              1        2        0          4
magneticacorn               4              1        1        0          4
KanetsuguNaoe               4              0        4        1          1
PM_ME_YOUR_MARS_BARS        4              0        0        1          1
kyleandrew_7                4              0        0        1          1
rapsin4lmao                 4              0        0        1          1
brandonouthouse             4              0        0        1          1
Cervix-Pounder              4              0        3        0          4
FitzRoyced                  4              0        2        0          4
Kindlydestroyed             4              0        2        0          4
saint-86                    4              0        1        0          4
3ch03d                      3              1        3        0          3
mdubyo                      3              1        2        0          3
Tutush                      3              1        2        0          3
NorwegianSaint              3              1        2        0          3
saintstu                    3              1        1        0          3
Tough-Whereas1205           3              1        1        0          3
zoinks10                    3              1        1        0          3
dan_3                       3              1        1        0          3
who905                      3              1        1        0          3
StreetSuspicious8456        3              0        3        1          0
HOWDY__YALL                 3              0        3        1          0
TheTyrantis                 3              0        3        1          0
Deadpooldan                 3              0        3        1          0
SomeGuyCalledPercy          3              0        0        1          0
uKrayZ                      3              0        0        1          0
GraveRaven                  3              0        3        0          3
Revolutionary_Cup602        3              0        2        0          3
delegod1                    3              0        2        0          3
tugboet                     3              0        2        0          3
thatcrazyhorse              3              0        1        0          3
MrJoshua_182                3              0        1        0          3
RuleBritannia1919           3              0        1        0          3
hahs95                      3              0        1        0          3
CelaenaSardothien007        3              0        1        0          3
Positive-Sound-4972         3              0        1        0          3
jackodriscol                3              0        0        0          3
JimmyRiddle707              3              0        0        0          3
Potato271                   3              0        0        0          3
Tspecs05                    2              1        2        0          2
oldredstang66               2              1        1        0          2
PhilipRobertson             2              1        1        0          2
GuteLord-                   2              1        1        0          2
LordOrtus                   2              1        1        0          2
Bayne7096                   2              1        1        0          2
gedly89                     2              1        1        0          2
Zstupple                    2              0        2        0          2
LovingCatholicPriest        2              0        2        0          2
BlameTibor                  2              0        2        0          2
Anglo-fornian               2              0        2        0          2
HelpfulSloth14              2              0        2        0          2
bendezhashein               2              0        2        0          2
Many_Background_3679        2              0        1        0          2
Desperate_Low9482           2              0        1        0          2
Lucky_Strike1               2              0        1        0          2
GordonRamsayGhost           2              0        1        0          2
spankeycakes                2              0        1        0          2
MangerDanger1               2              0        0        0          2
jayforplay                  2              0        0        0          2
accidentalsalmon            2              0        0        0          2
Relevant_Rev                2              0        0        0          2
Klutzy-Put-1786             2              0        0        0          2
Bruceplanet                 2              0        0        0          2
gubbyno                     1              1        1        0          1
Weary_Initiative5582        1              1        1        0          1
JoeGordon07                 1              1        1        0          1
LukeBron                    1              1        1        0          1
Opposite_Sir1549            1              1        1        0          1
parabola9999                1              1        1        0          1
fanea1                      1              1        1        0          1
Scared_Leading2875          1              1        1        0          1
craig_hoxton                1              1        1        0          1
igsey                       1              0        1        0          1
FluidSaint                  1              0        1        0          1
T_Hr0                       1              0        1        0          1
Finoptics                   1              0        1        0          1
mr_grission                 1              0        1        0          1
KingHarpoon616              1              0        1        0          1
chesterchugger              1              0        1        0          1
3rd__i                      1              0        1        0          1
baristaboy24                1              0        1        0          1
bathtub_not_beach           1              0        1        0          1
Fast-Engineer915            1              0        1        0          1
Zakedawn                    1              0        1        0          1
buddyomg                    1              0        1        0          1
Wafflz__                    1              0        1        0          1
BevvyTime                   1              0        1        0          1
galaxygalaxy777             1              0        1        0          1
Squm9                       1              0        1        0          1
Captain_Obvious_x           1              0        1        0          1
Fatty4forks                 1              0        1        0          1
wostmardin                  1              0        1        0          1
exhaleair                   1              0        1        0          1
kempston_joystick           1              0        1        0          1
rabbitradar                 1              0        1        0          1
TouristDramatic8295         1              0        1        0          1
kevmccartney                1              0        1        0          1
SoggyMattress2              1              0        1        0          1
boondocksaint08             1              0        1        0          1
OpScreechingHalt            1              0        1        0          1
Educational_Ad288           1              0        1        0          1
No_Amphibian6382            1              0        1        0          1
ThermoWizz                  1              0        1        0          1
GuyInWessex                 1              0        1        0          1
Likunandi                   1              0        1        0          1
Patentlyy                   1              0        1        0          1
Geralt0908                  1              0        1        0          1
Salt-Cup-2300               1              0        0        0          1
Blackgotham-12              1              0        0        0          1
Toast_for_President         1              0        0        0          1
jeromereyes                 1              0        0        0          1
asdaf22                     1              0        0        0          1
Adziboy                     1              0        0        0          1
Henghast                    1              0        0        0          1
rghsfc                      1              0        0        0          1
Weirdo_boy02                1              0        0        0          1
fluffyplayery               1              0        0        0          1
Ahegaopizza                 1              0        0        0          1
thisisclassicus             1              0        0        0          1
BanjoPants74                1              0        0        0          1
J_Dymond                    1              0        0        0          1
madshjort                   1              0        0        0          1
allbarneynorubble           1              0        0        0          1
DeadSpaceLover              1              0        0        0          1
BJH19                       1              0        0        0          1
496e636f676e69746f          1              0        0        0          1
aredditusername69           1              0        0        0          1
Holy_Shit_Balls_69          1              0        0        0          1
TrumpsCheetoJizz            1              0        0        0          1
Beardedmetalhead            1              0        0        0          1
Financial-Glass5693         1              0        0        0          1
alki07                      0              0        0        0          0
Antidote-Killer             0              0        0        0          0
MAFIAxMaverick              0              0        0        0          0
gooffking                   0              0        0        0          0
roberthart327               0              0        0        0          0
darave123                   0              0        0        0          0
Unlucky_Island_742          0              0        0        0          0
Vsovs                       0              0        0        0          0
WaltertheWobot              0              0        0        0          0
happysnappygoat             0              0        0        0          0
whowantstogo                0              0        0        0          0
frooberts                   0              0        0        0          0
K3GGY                       0              0        0        0          0
Dr-Honks                    0              0        0        0          0
EntersMikers                0              0        0        0          0
Hefty-Competition297        0              0        0        0          0
MrRyan1320                  0              0        0        0          0
sgm94                       0              0        0        0          0
guillotine-jones            0              0        0        0          0
Super-saints12              0              0        0        0          0
master_shifwho              0              0        0        0          0
GrandmasterYoda1            0              0        0        0          0
whattodotodo8               0              0        0        0          0
TheEggMan45                 0              0        0        0          0
gongasf                     0              0        0        0          0
pctomfor                    0              0        0        0          0
jrdn1616                    0              0        0        0          0
BlueInq                     0              0        0        0          0
bundy554                    0              0        0        0          0
Whenthebeatdropolis         0              0        0        0          0
street--donut               0              0        0        0          0
Glittering-Cow-4702         0              0        0        0          0
DrShaftmanPhD               0              0        0        0          0
Potential-Oil-1795          0              0        0        0          0
soverign_cheese             0              0        0        0          0
Lost_Disk                   0              0        0        0          0
BigTettenator               0              0        0        0          0
West_Equivalent7997         0              0        0        0          0
MonarchyBoner               0              0        0        0          0
Alina2017                   0              0        0        0          0
Cormac419                   0              0        0        0          0
King_Lamb                   0              0        0        0          0
PunnyIsNotFunny             0              0        0        0          0
weatherghost                0              0        0        0          0
Nervous_Jaguar_2826         0              0        0        0          0
throwaway1throwawa          0              0        0        0          0
jonnyhoots                  0              0        0        0          0
JoeBiggzDC                  0              0        0        0          0
LiveFree-603                0              0        0        0          0
TheHatThatTalks             0              0        0        0          0
Top_Dirt2557                0              0        0        0          0
Notional-                   0              0        0        0          0
BrandonPol                  0              0        0        0          0
Singh255                    0              0        0        0          0
King_PieNan                 0              0        0        0          0
Ok_Mix_3544                 0              0        0        0          0
matt_rev                    0              0        0        0          0
Mr_Yellow_Trousers          0              0        0        0          0
Magmar18                    0              0        0        0          0
neil2252                    0              0        0        0          0
No_Wrap_9979                0              0        0        0          0
istarisaints                0              0        0        0          0
FromTheEdgeOfTheDeep        0              0        0        0          0
Jamez_XIX                   0              0        0        0          0
Evening-Tart3067            0              0        0        0          0
mbridge2610                 0              0        0        0          0
senorbellend17              0              0        0        0          0
No_Pound5513                0              0        0        0          0
HorusHeresay                0              0        0        0          0
GreedoVision                0              0        0        0          0
TheSpitfires                0              0        0        0          0
fl0ralp                     0              0        0        0          0
Adventurous_Bass_673        0              0        0        0          0
YourWeekendDad              0              0        0        0          0
rigill                      0              0        0        0          0
nmc1995                     0              0        0        0          0
Same-Temporary8468          0              0        0        0          0
dinzil02                    0              0        0        0          0
Crazymorsejr                0              0        0        0          0
MerryRain                   0              0        0        0          0
Special_Tune9184            0              0        0        0          0
slashmpw                    0              0        0        0          0

                      Wrongs*  MaxStreak*
UserName
Nixstricks                  3           7
LegitimatePass6924          2           6
slugmaniac                  3           4
flailingpariah              1           6
Saint_Noog                  1           8
jjbc56                      2           8
halarhala                   1           5
Zapdosman                   2           5
HandsomedanNZ               3           6
MetaRift                    3           6
gradi3nt                    1           4
Emergency-Room-5484         1           4
Nas1729                     2           4
malkusm                     4           5
lemezier                    4           3
NagromNitsuj                2           5
teuridge                    2           4
Zou-KaiLi                   2           4

In [13]:
pt.summarize_standings_after(root, match_id)

{'TotalExacts': 6, 'TotalCorrects': 30}

# Post Template

## Todo

 - Add callouts for exacts and streaks

In [14]:
m_next = pt.match_metadata(root, match_id+1)
m_last = pt.match_metadata(root, match_id)

s_pred = pt.summarize_predictions(root, match_id - 1)
s_stand = pt.summarize_standings_after(root, match_id-1)

print(f"""
# Prediction Thread Match {match_id + 2}: {m_next["HomeClub"]} vs {m_next["AwayClub"]}

# Home - Away Format

 - Home: {m_next["HomeClub"]}
 - Away: {m_next["AwayClub"]}

# Game Rules

 - Post a top level comment in this thread at least one hour before kickoff, before lineups are posted.
 - Follow the format of this example comment: "0 - 3. Banter goes here."
 - Comment format must be "[Home Score] - [Away Score]. [Optional explanation, detailed prediction, or general shit talking here.]"
 - Scoring:
    - **3 points** for an exactly correct prediction.
    - **1 points** for a correct result.
    - **0 points** for an incorrect result.
- DM me with any problems, questions, comments.

# Summary of Last Match ({m_last["HomeClub"]} - {m_last["AwayClub"]})

{m_last["ThreadUrl"]}

 - Total Predictions: {s_pred["TotalPredictions"]}
 - Predicted Home Wins: {s_pred["TotalHomeWinPredictions"]} 
 - Predicted Away Wins: {s_pred["TotalAwayWinPredictions"]} 
 - Predicted Draws: {s_pred["TotalDrawPredictions"]}
 - Exacts: {s_stand["TotalExacts"]}
 - Corrects: {s_stand["TotalCorrects"]} 

# Standings
{new_standings.reset_index().to_markdown()}
""")

# Prediction Thread Match 12: Southampton vs Liverpool

# Home - Away Format

 - Home: Southampton
 - Away: Liverpool

# Game Rules

 - Post a top level comment in this thread at least one hour before kickoff, before lineups are posted.
 - Follow the format of this example comment: "0 - 3. Banter goes here."
 - Comment format must be "[Home Score] - [Away Score]. [Optional explanation, detailed prediction, or general shit talking here.]"
 - Scoring:
    - **3 points** for an exactly correct prediction.
    - **1 points** for a correct result.
    - **0 points** for an incorrect result.
- DM me with any problems, questions, comments.

# Summary of Last Match (Wolves - Southampton)

https://www.reddit.com/r/SaintsFC/comments/1gmw4bv/prediction_thread_match_11_wolves_southampton/

 - Total Predictions: 87
 - Predicted Home Wins: 46
 - Predicted Away Wins: 27
 - Predicted Draws: 14
 - Exacts: 7
 - Corrects: 39

# Standings
|     | UserName             |   Points |   PointsGained |   Streak |   Exacts |   Corrects |   Wrongs |   MaxStreak |
|----:|:---------------------|---------:|---------------:|---------:|---------:|-----------:|---------:|------------:|
|   0 | flailingpariah       |       13 |              3 |        3 |        2 |          7 |        2 |           6 |
|   1 | halarhala            |       13 |              1 |        8 |        2 |          7 |        1 |           8 |
|   2 | slugmaniac           |       13 |              0 |        4 |        3 |          4 |        3 |           4 |
|   3 | Nixstricks           |       13 |              0 |        0 |        3 |          4 |        4 |           7 |
|   4 | LegitimatePass6924   |       12 |              1 |        1 |        2 |          6 |        3 |           6 |
|   5 | Saint_Noog           |       12 |              0 |        0 |        2 |          6 |        2 |          11 |
|   6 | teuridge             |       10 |              3 |        3 |        1 |          7 |        3 |           4 |
|   7 | Nas1729              |       10 |              1 |        5 |        1 |          7 |        2 |           5 |
|   8 | Zapdosman            |       10 |              1 |        1 |        1 |          7 |        3 |           5 |
|   9 | malkusm              |       10 |              0 |        0 |        2 |          4 |        5 |           8 |
|  10 | Intermittent-Thinker |       10 |              0 |        0 |        1 |          7 |        3 |           7 |
|  11 | specifylength        |        9 |              1 |        8 |        1 |          6 |        3 |           8 |
|  12 | NagromNitsuj         |        9 |              1 |        3 |        1 |          6 |        2 |           5 |
|  13 | gradi3nt             |        9 |              1 |        1 |        0 |          9 |        2 |           4 |
|  14 | HandsomedanNZ        |        9 |              0 |        7 |        1 |          6 |        3 |           7 |
|  15 | jjbc56               |        9 |              0 |        0 |        1 |          6 |        3 |           8 |
|  16 | JAChambel            |        8 |              3 |        3 |        1 |          5 |        2 |           3 |
|  17 | pishkabob            |        8 |              1 |        5 |        0 |          8 |        3 |           5 |
|  18 | shontgomery          |        8 |              0 |        0 |        2 |          2 |        5 |           3 |
|  19 | MetaRift             |        8 |              0 |        0 |        1 |          5 |        5 |           6 |
|  20 | lemezier             |        8 |              0 |        0 |        1 |          5 |        5 |           3 |
|  21 | Emergency-Room-5484  |        8 |              0 |        0 |        0 |          8 |        2 |           4 |
|  22 | Cervix-Pounder       |        7 |              3 |        3 |        1 |          4 |        2 |           3 |
|  23 | chebalebs            |        7 |              1 |        1 |        1 |          4 |        4 |           3 |
|  24 | uuuuuuuhhhhh         |        7 |              1 |        3 |        0 |          7 |        4 |           3 |
|  25 | TheFuzzyEucalyptus   |        7 |              1 |        1 |        0 |          7 |        2 |           3 |
|  26 | UtterlyRedditculous  |        7 |              1 |        1 |        0 |          7 |        2 |           4 |
|  27 | strider_tom          |        7 |              1 |        1 |        0 |          7 |        4 |           4 |
|  28 | magneticacorn        |        7 |              0 |        4 |        1 |          4 |        5 |           4 |
|  29 | FalafelHalloumi      |        7 |              0 |        0 |        1 |          4 |        6 |           3 |
|  30 | benscott81           |        7 |              0 |        0 |        1 |          4 |        5 |           3 |
|  31 | Jpwf                 |        7 |              0 |        0 |        1 |          4 |        5 |           3 |
|  32 | ThatMoodyBstard      |        7 |              0 |        0 |        0 |          7 |        3 |           4 |
|  33 | Zou-KaiLi            |        7 |              0 |        0 |        0 |          7 |        3 |           4 |
|  34 | Hot_Chair_7523       |        6 |              1 |        1 |        1 |          3 |        6 |           3 |
|  35 | meteoritee           |        6 |              1 |        6 |        0 |          6 |        0 |           6 |
|  36 | thinlike_napkins     |        6 |              1 |        1 |        0 |          6 |        2 |           3 |
|  37 | nape27               |        6 |              1 |        1 |        0 |          6 |        5 |           2 |
|  38 | fcf4                 |        6 |              0 |        5 |        1 |          3 |        1 |           5 |
|  39 | redditbanana42       |        6 |              0 |        0 |        1 |          3 |        7 |           3 |
|  40 | fartarus             |        6 |              0 |        0 |        0 |          6 |        5 |           2 |
|  41 | Boring_Inflation1494 |        6 |              0 |        0 |        0 |          6 |        2 |           5 |
|  42 | craig_hoxton         |        5 |              3 |        5 |        1 |          2 |        0 |           5 |
|  43 | BFT_022              |        5 |              1 |        1 |        0 |          5 |        1 |           4 |
|  44 | lakermamba1999       |        5 |              0 |        1 |        1 |          2 |        1 |           4 |
|  45 | mcsgwigga            |        5 |              0 |        0 |        0 |          5 |        6 |           3 |
|  46 | infestationE15       |        5 |              0 |        0 |        0 |          5 |        5 |           2 |
|  47 | Geralt0908           |        4 |              3 |        3 |        1 |          1 |        2 |           3 |
|  48 | GraveRaven           |        4 |              1 |        4 |        0 |          4 |        0 |           4 |
|  49 | HelpfulSloth14       |        4 |              1 |        4 |        0 |          4 |        0 |           4 |
|  50 | Tutush               |        4 |              1 |        3 |        0 |          4 |        1 |           3 |
|  51 | Potato271            |        4 |              1 |        1 |        0 |          4 |        5 |           2 |
|  52 | MrJoshua_182         |        4 |              1 |        1 |        0 |          4 |        4 |           1 |
|  53 | Positive-Sound-4972  |        4 |              1 |        1 |        0 |          4 |        4 |           1 |
|  54 | tugboet              |        4 |              1 |        1 |        0 |          4 |        5 |           2 |
|  55 | saintstu             |        4 |              1 |        1 |        0 |          4 |        7 |           1 |
|  56 | KanetsuguNaoe        |        4 |              0 |        4 |        1 |          1 |        1 |           4 |
|  57 | JoshHQ               |        4 |              0 |        4 |        1 |          1 |        0 |           4 |
|  58 | PM_ME_YOUR_MARS_BARS |        4 |              0 |        0 |        1 |          1 |        2 |           4 |
|  59 | kyleandrew_7         |        4 |              0 |        0 |        1 |          1 |        5 |           3 |
|  60 | rapsin4lmao          |        4 |              0 |        0 |        1 |          1 |        1 |           4 |
|  61 | brandonouthouse      |        4 |              0 |        0 |        1 |          1 |        4 |           3 |
|  62 | hAkonf               |        4 |              0 |        2 |        0 |          4 |        2 |           2 |
|  63 | saint-86             |        4 |              0 |        1 |        0 |          4 |        2 |           2 |
|  64 | FitzRoyced           |        4 |              0 |        0 |        0 |          4 |        3 |           2 |
|  65 | Kindlydestroyed      |        4 |              0 |        0 |        0 |          4 |        2 |           2 |
|  66 | JimmyRiddle707       |        4 |              0 |        0 |        0 |          4 |        6 |           1 |
|  67 | CelaenaSardothien007 |        4 |              0 |        0 |        0 |          4 |        4 |           2 |
|  68 | Tough-Whereas1205    |        4 |              0 |        0 |        0 |          4 |        5 |           2 |
|  69 | zoinks10             |        4 |              0 |        0 |        0 |          4 |        6 |           2 |
|  70 | who905               |        4 |              0 |        0 |        0 |          4 |        5 |           2 |
|  71 | StreetSuspicious8456 |        3 |              0 |        3 |        1 |          0 |        0 |           3 |
|  72 | HOWDY__YALL          |        3 |              0 |        3 |        1 |          0 |        0 |           3 |
|  73 | TheTyrantis          |        3 |              0 |        3 |        1 |          0 |        0 |           3 |
|  74 | Deadpooldan          |        3 |              0 |        3 |        1 |          0 |        0 |           3 |
|  75 | SomeGuyCalledPercy   |        3 |              0 |        0 |        1 |          0 |        1 |           3 |
|  76 | uKrayZ               |        3 |              0 |        0 |        1 |          0 |        1 |           3 |
|  77 | 3ch03d               |        3 |              0 |        3 |        0 |          3 |        2 |           3 |
|  78 | Revolutionary_Cup602 |        3 |              0 |        2 |        0 |          3 |        1 |           2 |
|  79 | delegod1             |        3 |              0 |        2 |        0 |          3 |        3 |           2 |
|  80 | mdubyo               |        3 |              0 |        2 |        0 |          3 |        2 |           2 |
|  81 | RuleBritannia1919    |        3 |              0 |        1 |        0 |          3 |        1 |           2 |
|  82 | hahs95               |        3 |              0 |        1 |        0 |          3 |        1 |           2 |
|  83 | MangerDanger1        |        3 |              0 |        1 |        0 |          3 |        4 |           1 |
|  84 | Relevant_Rev         |        3 |              0 |        1 |        0 |          3 |        6 |           1 |
|  85 | jackodriscol         |        3 |              0 |        0 |        0 |          3 |        2 |           3 |
|  86 | dan_3                |        3 |              0 |        0 |        0 |          3 |        7 |           1 |
|  87 | NorwegianSaint       |        3 |              0 |        0 |        0 |          3 |        4 |           2 |
|  88 | thatcrazyhorse       |        3 |              0 |        0 |        0 |          3 |        4 |           1 |
|  89 | Bruceplanet          |        3 |              0 |        0 |        0 |          3 |        7 |           1 |
|  90 | oldredstang66        |        3 |              0 |        0 |        0 |          3 |        6 |           2 |
|  91 | kempston_joystick    |        2 |              1 |        2 |        0 |          2 |        2 |           2 |
|  92 | Lost_Disk            |        2 |              1 |        2 |        0 |          2 |        3 |           2 |
|  93 | BanjoPants74         |        2 |              1 |        1 |        0 |          2 |        1 |           1 |
|  94 | Zstupple             |        2 |              0 |        2 |        0 |          2 |        0 |           2 |
|  95 | LovingCatholicPriest |        2 |              0 |        2 |        0 |          2 |        1 |           2 |
|  96 | Anglo-fornian        |        2 |              0 |        2 |        0 |          2 |        2 |           2 |
|  97 | Likunandi            |        2 |              0 |        2 |        0 |          2 |        0 |           2 |
|  98 | Opposite_Sir1549     |        2 |              0 |        2 |        0 |          2 |        0 |           2 |
|  99 | Many_Background_3679 |        2 |              0 |        1 |        0 |          2 |        2 |           1 |
| 100 | Lucky_Strike1        |        2 |              0 |        1 |        0 |          2 |        5 |           1 |
| 101 | GordonRamsayGhost    |        2 |              0 |        1 |        0 |          2 |        1 |           1 |
| 102 | PhilipRobertson      |        2 |              0 |        1 |        0 |          2 |        2 |           1 |
| 103 | GuteLord-            |        2 |              0 |        1 |        0 |          2 |        2 |           1 |
| 104 | LordOrtus            |        2 |              0 |        1 |        0 |          2 |        3 |           1 |
| 105 | Bayne7096            |        2 |              0 |        1 |        0 |          2 |        3 |           1 |
| 106 | gedly89              |        2 |              0 |        1 |        0 |          2 |        4 |           1 |
| 107 | jeromereyes          |        2 |              0 |        1 |        0 |          2 |        1 |           1 |
| 108 | Weirdo_boy02         |        2 |              0 |        1 |        0 |          2 |        3 |           1 |
| 109 | jayforplay           |        2 |              0 |        0 |        0 |          2 |        2 |           1 |
| 110 | accidentalsalmon     |        2 |              0 |        0 |        0 |          2 |        2 |           2 |
| 111 | Klutzy-Put-1786      |        2 |              0 |        0 |        0 |          2 |        2 |           1 |
| 112 | spankeycakes         |        2 |              0 |        0 |        0 |          2 |        6 |           1 |
| 113 | BlameTibor           |        2 |              0 |        0 |        0 |          2 |        2 |           2 |
| 114 | bendezhashein        |        2 |              0 |        0 |        0 |          2 |        1 |           2 |
| 115 | Desperate_Low9482    |        2 |              0 |        0 |        0 |          2 |        5 |           1 |
| 116 | Tspecs05             |        2 |              0 |        0 |        0 |          2 |        7 |           2 |
| 117 | DeadSpaceLover       |        2 |              0 |        0 |        0 |          2 |        3 |           1 |
| 118 | aredditusername69    |        2 |              0 |        0 |        0 |          2 |        4 |           1 |
| 119 | Weary_Initiative5582 |        2 |              0 |        0 |        0 |          2 |        4 |           2 |
| 120 | InfernoTurnip        |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
| 121 | igsey                |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 122 | FluidSaint           |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 123 | T_Hr0                |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 124 | Finoptics            |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 125 | mr_grission          |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 126 | KingHarpoon616       |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 127 | chesterchugger       |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 128 | 3rd__i               |        1 |              0 |        1 |        0 |          1 |        3 |           1 |
| 129 | baristaboy24         |        1 |              0 |        1 |        0 |          1 |        1 |           1 |
| 130 | bathtub_not_beach    |        1 |              0 |        1 |        0 |          1 |        1 |           1 |
| 131 | Fast-Engineer915     |        1 |              0 |        1 |        0 |          1 |        1 |           1 |
| 132 | Zakedawn             |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 133 | buddyomg             |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 134 | Wafflz__             |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 135 | BevvyTime            |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 136 | galaxygalaxy777      |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 137 | Squm9                |        1 |              0 |        1 |        0 |          1 |        1 |           1 |
| 138 | Captain_Obvious_x    |        1 |              0 |        1 |        0 |          1 |        1 |           1 |
| 139 | Fatty4forks          |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 140 | exhaleair            |        1 |              0 |        1 |        0 |          1 |        3 |           1 |
| 141 | rabbitradar          |        1 |              0 |        1 |        0 |          1 |        2 |           1 |
| 142 | TouristDramatic8295  |        1 |              0 |        1 |        0 |          1 |        1 |           1 |
| 143 | kevmccartney         |        1 |              0 |        1 |        0 |          1 |        1 |           1 |
| 144 | SoggyMattress2       |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 145 | boondocksaint08      |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 146 | OpScreechingHalt     |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 147 | Educational_Ad288    |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 148 | No_Amphibian6382     |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 149 | ThermoWizz           |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 150 | GuyInWessex          |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 151 | Patentlyy            |        1 |              0 |        1 |        0 |          1 |        1 |           1 |
| 152 | JoeGordon07          |        1 |              0 |        1 |        0 |          1 |        1 |           1 |
| 153 | fanea1               |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 154 | Scared_Leading2875   |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 155 | whattodotodo8        |        1 |              0 |        1 |        0 |          1 |        8 |           1 |
| 156 | Suspicious-Living683 |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 157 | ShadowedEclipse      |        1 |              0 |        1 |        0 |          1 |        0 |           1 |