Schema

 - Matches:
     - MatchId: int
         - MatchWeek: int
         - HomeTeam: int
         - AwayTeam: int
         - MatchResult: pt.MatchResult
         - ThreadUrl: str
         - MatchTime: datetime (convert to UTC?)

 - Standings:
     - MatchId: int
         - UserName: str
             - Points: int

 - Predictions:
     - MatchId: int
         - UserName: str
             - Comment: str
             - CommentTime: datetime (convert to UTC?)


What if someone posts two comments?

{
    "MatchId": {
        "0": {
            "MatchWeek": 0,
            "HomeTeam": "Southampton",
            "
        }
    }
}

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from pathlib import Path
import pandas as pd
from icecream import ic

import predthread as pt
from predthread import fbref

from collections import defaultdict
from copy import deepcopy

In [3]:
root = Path(".").absolute()
print(root)

/Users/julianirwin/Projects/predthread/examples/southamton_24-25_33c895d4

In [4]:
club_names = pt.club_names(root)
api_keys = pt.api_keys(root)
match_metadata = pt.match_metadata(root, match_id=0)
matches_metadata = pt.matches_metadata(root)
matches_metadata_df = pt.matches_metadata_df(root)

# ic(club_names)
# ic(match_metadata)
# ic(matches_metadata)

In [11]:
# Of last completed match
match_id = 2

In [9]:
# Using matchweek, not match id
ic(fbref.match_metadata(i_matchweek=4))
pass

ic| fbref.match_metadata(i_matchweek=4): {'AwayClub': 'Manchester Utd',
                                          'AwayGoals': '',
                                          'HomeClub': 'Southampton',
                                          'HomeGoals': '',
                                          'MatchTimeUtc': '2024-09-14T12:30:00Z',
                                          'MatchWeek': 4,
                                          'ThreadUrl': ''}

In [10]:
pt.append_match_metadata(root, fbref.match_metadata(4))

In [12]:
pd.set_option("display.max_rows", None)
ps = pt.download_predictions(root, match_id)
ps.sort_values(["PredictedHomeGoals", "PredictedAwayGoals"], ascending=False)
# ps

,Comment,PredictedHomeGoals,PredictedAwayGoals
UserName,,,
nape27,3-2,3,2
flailingpariah,3-1 to Brentford. Unrelenting pessimism campai...,3,1
chebalebs,3-1,3,1
StreetSuspicious8456,3-1 saints,3,1
LegitimatePass6924,3-1,3,1
lemezier,3-1,3,1
GordonRamsayGhost,3-0,3,0
thinlike_napkins,3-0,3,0
uuuuuuuhhhhh,3-0,3,0
LordOrtus,3-0,3,0
strider_tom,3-0 Brentford,3,0
3ch03d,2-3,2,3
TheHatThatTalks,2-3. I hope we’re buzzing from the Cardiff mat...,2,3
Holy_Shit_Balls_69,2-3,2,3
wostmardin,2-3,2,3
jjbc56,2-2,2,2
saintstu,2-2,2,2
redditbanana42,2-2,2,2
FalafelHalloumi,2-2,2,2
mcsgwigga,2-2,2,2
hAkonf,2-2,2,2
brandonouthouse,2-2,2,2
gradi3nt,2-1,2,1
pishkabob,2-1,2,1
jackodriscol,2-1,2,1
fcf4,2-1,2,1
madshjort,2-1 close but no cake,2,1
CelaenaSardothien007,2-1,2,1
Zapdosman,2-1,2,1
Bruceplanet,2-1 if we can create any scoring opportunities...,2,1
accidentalsalmon,2-1 Brentford,2,1
UtterlyRedditculous,2-1,2,1
Zou-KaiLi,2-1,2,1
ThatMoodyBstard,2-1,2,1
hahs95,2-1,2,1
lakermamba1999,2-1,2,1
saint-86,2-0 Bees. Let’s see if pessimism helps,2,0
fartarus,2-0,2,0
Nas1729,2-0,2,0
Intermittent-Thinker,2 - 0,2,0
Emergency-Room-5484,2-0,2,0
J_Dymond,2-0 Brentford,2,0
MangerDanger1,2-0,2,0
jayforplay,2-0,2,0
Saint_Noog,2-0 Brentford. We always lose when I go to aw...,2,0
Revolutionary_Cup602,2 - 0,2,0
FitzRoyced,2-0,2,0
teuridge,2-0,2,0
RuleBritannia1919,2-0,2,0
Antidote-Killer,1-7,1,7
Relevant_Rev,1-4 saints,1,4
Unlucky_Island_742,1-3,1,3
whowantstogo,1-3 saints,1,3
malkusm,1-2 weirdly optimistic,1,2
kempston_joystick,1-2,1,2
gongasf,Brentford 1-2 Saints,1,2
Tspecs05,1-2,1,2
zoinks10,1:2 - we'll discover where the other net is,1,2
delegod1,1-2,1,2
who905,1-2,1,2
spankeycakes,1-2,1,2
HandsomedanNZ,1-2\n\nSurely a win is due?,1,2
Ahegaopizza,1-2 COYS,1,2
Desperate_Low9482,1-2,1,2
Hefty-Competition297,1-2 COYR,1,2
oldredstang66,1-2,1,2
Fast-Engineer915,1-2 saints 🙏,1,2
Potato271,1-1. We dominate the ball for 80 minutes but f...,1,1
slugmaniac,1-1,1,1
LiveFree-603,1-1,1,1
Top_Dirt2557,1-1,1,1
bathtub_not_beach,1-1,1,1
MetaRift,1-1,1,1
Notional-,1-1\nOur first point,1,1
Jpwf,1-1,1,1
BigTettenator,1-1,1,1
NorwegianSaint,1-1,1,1
magneticacorn,1-1,1,1
thisisclassicus,1-1,1,1
Lucky_Strike1,1-1,1,1
JimmyRiddle707,1-1,1,1
3rd__i,1-1 somehow,1,1
Blackgotham-12,1-1,1,1
Nixstricks,1-0 A set piece gets us once again.,1,0
meteoritee,1-0,1,0
tugboet,1-0 again,1,0
sgm94,0-3 cardif was a wake up and now we roll,0,3
whattodotodo8,0-2 Saints Win!,0,2
jonnyhoots,0-1,0,1
JoeBiggzDC,"""0-1",0,1
darave123,0-1,0,1
thatcrazyhorse,0-1,0,1
mdubyo,0-1\n\nJust have a feeling.,0,1
Salt-Cup-2300,0-1 please,0,1
pctomfor,0 - 0. Defense is gelling but still working o...,0,0

In [13]:
pt.summarize_predictions(root, match_id)

{'TotalPredictions': 95,
 'TotalHomeWinPredictions': 41,
 'TotalAwayWinPredictions': 30,
 'TotalDrawPredictions': 24}

In [ ]:
ps.loc["SomeGuyCalledPercy"]

In [14]:
new_standings = pt.calculate_updated_standings_after(root, match_id)
new_standings

,Points,PointsGained,Streak,Exacts,Corrects,Wrongs,MaxStreak
UserName,,,,,,,
flailingpariah,5,3,5,1,2,0,5
LegitimatePass6924,4,3,3,1,1,1,3
chebalebs,4,3,3,1,1,1,3
lemezier,4,3,3,1,1,1,3
Nixstricks,4,1,1,1,1,1,3
PM_ME_YOUR_MARS_BARS,4,0,4,1,1,0,4
halarhala,4,0,4,1,1,0,4
slugmaniac,4,0,0,1,1,1,4
StreetSuspicious8456,3,3,3,1,0,0,3
gradi3nt,3,1,3,0,3,0,3
jackodriscol,3,1,3,0,3,0,3
Emergency-Room-5484,3,1,3,0,3,0,3
ThatMoodyBstard,3,1,3,0,3,0,3
UtterlyRedditculous,3,1,3,0,3,0,3
Jpwf,3,0,0,1,0,2,3
shontgomery,3,0,0,1,0,1,3
SomeGuyCalledPercy,3,0,0,1,0,1,3
thinlike_napkins,2,1,2,0,2,0,2
meteoritee,2,1,2,0,2,0,2
Zapdosman,2,1,1,0,2,1,1
teuridge,2,1,1,0,2,1,1
MangerDanger1,2,1,1,0,2,1,1
uuuuuuuhhhhh,2,1,1,0,2,1,1
Saint_Noog,2,1,1,0,2,1,1
fcf4,2,1,1,0,2,1,1
Zou-KaiLi,2,1,1,0,2,1,1
fartarus,2,1,1,0,2,1,1
Revolutionary_Cup602,2,1,1,0,2,1,1
jayforplay,2,1,1,0,2,1,1
FitzRoyced,2,1,1,0,2,1,1
nape27,2,1,1,0,2,1,1
saint-86,2,1,1,0,2,1,1
Nas1729,2,1,1,0,2,1,1
Intermittent-Thinker,2,1,1,0,2,1,1
pishkabob,2,1,1,0,2,1,1
CelaenaSardothien007,2,1,1,0,2,1,1
Zstupple,2,0,2,0,2,0,2
TheFuzzyEucalyptus,2,0,2,0,2,0,2
JAChambel,2,0,2,0,2,0,2
FalafelHalloumi,2,0,0,0,2,1,2
Bruceplanet,1,1,1,0,1,2,1
strider_tom,1,1,1,0,1,2,1
J_Dymond,1,1,1,0,1,2,1
accidentalsalmon,1,1,1,0,1,1,1
madshjort,1,1,1,0,1,1,1
tugboet,1,1,1,0,1,1,1
LordOrtus,1,1,1,0,1,1,1
GordonRamsayGhost,1,1,1,0,1,0,1
hahs95,1,1,1,0,1,0,1
lakermamba1999,1,1,1,0,1,0,1
RuleBritannia1919,1,1,1,0,1,0,1
igsey,1,0,1,0,1,0,1
FluidSaint,1,0,1,0,1,0,1
bendezhashein,1,0,1,0,1,0,1
T_Hr0,1,0,1,0,1,0,1
Finoptics,1,0,1,0,1,0,1
mr_grission,1,0,1,0,1,0,1
KingHarpoon616,1,0,1,0,1,0,1
chesterchugger,1,0,1,0,1,0,1
GuteLord-,1,0,1,0,1,0,1
BanjoPants74,1,0,1,0,1,0,1
Kindlydestroyed,1,0,1,0,1,0,1
BlameTibor,1,0,1,0,1,0,1
jjbc56,1,0,0,0,1,2,1
Tutush,1,0,0,0,1,1,1
Salt-Cup-2300,1,0,0,0,1,2,1
delegod1,1,0,0,0,1,2,1
HandsomedanNZ,1,0,0,0,1,2,1
Many_Background_3679,1,0,0,0,1,1,1
thatcrazyhorse,1,0,0,0,1,2,1
mcsgwigga,1,0,0,0,1,2,1
Cervix-Pounder,1,0,0,0,1,1,1
Positive-Sound-4972,1,0,0,0,1,1,1
Blackgotham-12,1,0,0,0,1,2,1
Toast_for_President,1,0,0,0,1,1,1
NagromNitsuj,1,0,0,0,1,1,1
specifylength,1,0,0,0,1,1,1
saintstu,1,0,0,0,1,2,1
infestationE15,1,0,0,0,1,1,1
benscott81,1,0,0,0,1,1,1
jeromereyes,1,0,0,0,1,1,1
asdaf22,1,0,0,0,1,1,1
Potato271,1,0,0,0,1,2,1
Tough-Whereas1205,1,0,0,0,1,1,1
Adziboy,1,0,0,0,1,1,1
Henghast,1,0,0,0,1,1,1
oldredstang66,1,0,0,0,1,2,1
magneticacorn,1,0,0,0,1,2,1
rghsfc,1,0,0,0,1,1,1
Weirdo_boy02,1,0,0,0,1,1,1
Desperate_Low9482,1,0,0,0,1,2,1
brandonouthouse,1,0,0,0,1,2,1
fluffyplayery,1,0,0,0,1,1,1
Lucky_Strike1,1,0,0,0,1,2,1
mdubyo,1,0,0,0,1,2,1
kyleandrew_7,1,0,0,0,1,1,1
malkusm,1,0,0,0,1,2,1
Ahegaopizza,1,0,0,0,1,2,1
MrJoshua_182,1,0,0,0,1,1,1
PhilipRobertson,1,0,0,0,1,1,1
MetaRift,1,0,0,0,1,2,1
JimmyRiddle707,1,0,0,0,1,2,1
thisisclassicus,1,0,0,0,1,1,1
hAkonf,1,0,0,0,1,1,1
NorwegianSaint,1,0,0,0,1,1,1
alki07,0,0,0,0,0,1,0
Antidote-Killer,0,0,0,0,0,3,0
wostmardin,0,0,0,0,0,3,0
MAFIAxMaverick,0,0,0,0,0,2,0
gooffking,0,0,0,0,0,2,0
Relevant_Rev,0,0,0,0,0,3,0
spankeycakes,0,0,0,0,0,2,0
roberthart327,0,0,0,0,0,1,0
darave123,0,0,0,0,0,3,0
Unlucky_Island_742,0,0,0,0,0,2,0
redditbanana42,0,0,0,0,0,3,0
Vsovs,0,0,0,0,0,1,0
WaltertheWobot,0,0,0,0,0,1,0
dan_3,0,0,0,0,0,2,0
happysnappygoat,0,0,0,0,0,1,0
whowantstogo,0,0,0,0,0,3,0
frooberts,0,0,0,0,0,1,0
gedly89,0,0,0,0,0,2,0
K3GGY,0,0,0,0,0,1,0
Dr-Honks,0,0,0,0,0,2,0
EntersMikers,0,0,0,0,0,1,0
Hefty-Competition297,0,0,0,0,0,3,0
Patentlyy,0,0,0,0,0,1,0
MrRyan1320,0,0,0,0,0,2,0
sgm94,0,0,0,0,0,3,0
Tspecs05,0,0,0,0,0,3,0
guillotine-jones,0,0,0,0,0,2,0
Super-saints12,0,0,0,0,0,1,0
3rd__i,0,0,0,0,0,3,0
Hot_Chair_7523,0,0,0,0,0,2,0
master_shifwho,0,0,0,0,0,2,0
GrandmasterYoda1,0,0,0,0,0,1,0
whattodotodo8,0,0,0,0,0,3,0
Anglo-fornian,0,0,0,0,0,2,0
TheEggMan45,0,0,0,0,0,1,0
gongasf,0,0,0,0,0,2,0
pctomfor,0,0,0,0,0,2,0
jrdn1616,0,0,0,0,0,1,0
BlueInq,0,0,0,0,0,1,0
bundy554,0,0,0,0,0,1,0
BJH19,0,0,0,0,0,1,0
Whenthebeatdropolis,0,0,0,0,0,1,0
who905,0,0,0,0,0,2,0
street--donut,0,0,0,0,0,1,0
3ch03d,0,0,0,0,0,2,0
Glittering-Cow-4702,0,0,0,0,0,1,0
496e636f676e69746f,0,0,0,0,0,1,0
DrShaftmanPhD,0,0,0,0,0,1,0
baristaboy24,0,0,0,0,0,1,0
Potential-Oil-1795,0,0,0,0,0,1,0
soverign_cheese,0,0,0,0,0,1,0
Lost_Disk,0,0,0,0,0,1,0
BigTettenator,0,0,0,0,0,2,0
West_Equivalent7997,0,0,0,0,0,1,0
exhaleair,0,0,0,0,0,1,0
kempston_joystick,0,0,0,0,0,2,0
MonarchyBoner,0,0,0,0,0,1,0
Alina2017,0,0,0,0,0,1,0
LovingCatholicPriest,0,0,0,0,0,1,0
Cormac419,0,0,0,0,0,1,0
zoinks10,0,0,0,0,0,2,0
aredditusername69,0,0,0,0,0,1,0
gubbyno,0,0,0,0,0,1,0
Bayne7096,0,0,0,0,0,1,0
King_Lamb,0,0,0,0,0,1,0
PunnyIsNotFunny,0,0,0,0,0,1,0
weatherghost,0,0,0,0,0,1,0
Nervous_Jaguar_2826,0,0,0,0,0,1,0
allbarneynorubble,0,0,0,0,0,1,0
Weary_Initiative5582,0,0,0,0,0,1,0
Holy_Shit_Balls_69,0,0,0,0,0,2,0
throwaway1throwawa,0,0,0,0,0,1,0
jonnyhoots,0,0,0,0,0,1,0
JoeBiggzDC,0,0,0,0,0,1,0
LiveFree-603,0,0,0,0,0,1,0
TheHatThatTalks,0,0,0,0,0,1,0
Top_Dirt2557,0,0,0,0,0,1,0
bathtub_not_beach,0,0,0,0,0,1,0
Notional-,0,0,0,0,0,1,0
Fast-Engineer915,0,0,0,0,0,1,0

In [ ]:
print(new_standings.reset_index().to_markdown())

In [ ]:
predictions = pt.load_predictions(root, match_id)
old_standings = pt.load_standings_after(root, match_id - 1)
new_standings_p = pt.load_standings_after(root, match_id)
new_standings_p = new_standings.rename(columns=lambda x: x + "*")
predictions.join(old_standings, new_standings_p)

In [15]:
pt.summarize_standings_after(root, match_id)

{'TotalExacts': 5, 'TotalCorrects': 36}

# Post Template

In [16]:
m_next = pt.match_metadata(root, match_id+1)
m_last = pt.match_metadata(root, match_id)

s_pred = pt.summarize_predictions(root, match_id - 1)
s_stand = pt.summarize_standings_after(root, match_id-1)

print(f"""
# Prediction Thread Match {match_id + 2}: {m_next["HomeClub"]} vs {m_next["AwayClub"]}

# Home - Away Format

 - Home: {m_next["HomeClub"]}
 - Away: {m_next["AwayClub"]}

# Game Rules

 - Post a top level comment in this thread at least one hour before kickoff, before lineups are posted.
 - Follow the format of this example comment: "0 - 3. Banter goes here."
 - Comment format must be "[Home Score] - [Away Score]. [Optional explanation, detailed prediction, or general shit talking here.]"
 - Scoring:
    - **3 points** for an exactly correct prediction.
    - **1 points** for a correct result.
    - **0 points** for an incorrect result.
- DM me with any problems, questions, comments.

# Summary of Last Match ({m_last["HomeClub"]} - {m_last["AwayClub"]})

{m_last["ThreadUrl"]}

 - Total Predictions: {s_pred["TotalPredictions"]}
 - Predicted Home Wins: {s_pred["TotalHomeWinPredictions"]} 
 - Predicted Away Wins: {s_pred["TotalAwayWinPredictions"]} 
 - Predicted Draws: {s_pred["TotalDrawPredictions"]}
 - Exacts: {s_stand["TotalExacts"]}
 - Corrects: {s_stand["TotalCorrects"]} 

# Standings
{new_standings.reset_index().to_markdown()}
""")

# Prediction Thread Match 4: Southampton vs Manchester Utd

# Home - Away Format

 - Home: Southampton
 - Away: Manchester Utd

# Game Rules

 - Post a top level comment in this thread at least one hour before kickoff, before lineups are posted.
 - Follow the format of this example comment: "0 - 3. Banter goes here."
 - Comment format must be "[Home Score] - [Away Score]. [Optional explanation, detailed prediction, or general shit talking here.]"
 - Scoring:
    - **3 points** for an exactly correct prediction.
    - **1 points** for a correct result.
    - **0 points** for an incorrect result.
- DM me with any problems, questions, comments.

# Summary of Last Match (Brentford - Southampton)

https://www.reddit.com/r/SaintsFC/comments/1f4j1xz/prediction_thread_match_3_brentford_vs_southampton/

 - Total Predictions: 147
 - Predicted Home Wins: 101
 - Predicted Away Wins: 18
 - Predicted Draws: 28
 - Exacts: 3
 - Corrects: 15

# Standings
|     | UserName             |   Points |   PointsGained |   Streak |   Exacts |   Corrects |   Wrongs |   MaxStreak |
|----:|:---------------------|---------:|---------------:|---------:|---------:|-----------:|---------:|------------:|
|   0 | flailingpariah       |        5 |              3 |        5 |        1 |          2 |        0 |           5 |
|   1 | LegitimatePass6924   |        4 |              3 |        3 |        1 |          1 |        1 |           3 |
|   2 | chebalebs            |        4 |              3 |        3 |        1 |          1 |        1 |           3 |
|   3 | lemezier             |        4 |              3 |        3 |        1 |          1 |        1 |           3 |
|   4 | Nixstricks           |        4 |              1 |        1 |        1 |          1 |        1 |           3 |
|   5 | PM_ME_YOUR_MARS_BARS |        4 |              0 |        4 |        1 |          1 |        0 |           4 |
|   6 | halarhala            |        4 |              0 |        4 |        1 |          1 |        0 |           4 |
|   7 | slugmaniac           |        4 |              0 |        0 |        1 |          1 |        1 |           4 |
|   8 | StreetSuspicious8456 |        3 |              3 |        3 |        1 |          0 |        0 |           3 |
|   9 | gradi3nt             |        3 |              1 |        3 |        0 |          3 |        0 |           3 |
|  10 | jackodriscol         |        3 |              1 |        3 |        0 |          3 |        0 |           3 |
|  11 | Emergency-Room-5484  |        3 |              1 |        3 |        0 |          3 |        0 |           3 |
|  12 | ThatMoodyBstard      |        3 |              1 |        3 |        0 |          3 |        0 |           3 |
|  13 | UtterlyRedditculous  |        3 |              1 |        3 |        0 |          3 |        0 |           3 |
|  14 | Jpwf                 |        3 |              0 |        0 |        1 |          0 |        2 |           3 |
|  15 | shontgomery          |        3 |              0 |        0 |        1 |          0 |        1 |           3 |
|  16 | SomeGuyCalledPercy   |        3 |              0 |        0 |        1 |          0 |        1 |           3 |
|  17 | thinlike_napkins     |        2 |              1 |        2 |        0 |          2 |        0 |           2 |
|  18 | meteoritee           |        2 |              1 |        2 |        0 |          2 |        0 |           2 |
|  19 | Zapdosman            |        2 |              1 |        1 |        0 |          2 |        1 |           1 |
|  20 | teuridge             |        2 |              1 |        1 |        0 |          2 |        1 |           1 |
|  21 | MangerDanger1        |        2 |              1 |        1 |        0 |          2 |        1 |           1 |
|  22 | uuuuuuuhhhhh         |        2 |              1 |        1 |        0 |          2 |        1 |           1 |
|  23 | Saint_Noog           |        2 |              1 |        1 |        0 |          2 |        1 |           1 |
|  24 | fcf4                 |        2 |              1 |        1 |        0 |          2 |        1 |           1 |
|  25 | Zou-KaiLi            |        2 |              1 |        1 |        0 |          2 |        1 |           1 |
|  26 | fartarus             |        2 |              1 |        1 |        0 |          2 |        1 |           1 |
|  27 | Revolutionary_Cup602 |        2 |              1 |        1 |        0 |          2 |        1 |           1 |
|  28 | jayforplay           |        2 |              1 |        1 |        0 |          2 |        1 |           1 |
|  29 | FitzRoyced           |        2 |              1 |        1 |        0 |          2 |        1 |           1 |
|  30 | nape27               |        2 |              1 |        1 |        0 |          2 |        1 |           1 |
|  31 | saint-86             |        2 |              1 |        1 |        0 |          2 |        1 |           1 |
|  32 | Nas1729              |        2 |              1 |        1 |        0 |          2 |        1 |           1 |
|  33 | Intermittent-Thinker |        2 |              1 |        1 |        0 |          2 |        1 |           1 |
|  34 | pishkabob            |        2 |              1 |        1 |        0 |          2 |        1 |           1 |
|  35 | CelaenaSardothien007 |        2 |              1 |        1 |        0 |          2 |        1 |           1 |
|  36 | Zstupple             |        2 |              0 |        2 |        0 |          2 |        0 |           2 |
|  37 | TheFuzzyEucalyptus   |        2 |              0 |        2 |        0 |          2 |        0 |           2 |
|  38 | JAChambel            |        2 |              0 |        2 |        0 |          2 |        0 |           2 |
|  39 | FalafelHalloumi      |        2 |              0 |        0 |        0 |          2 |        1 |           2 |
|  40 | Bruceplanet          |        1 |              1 |        1 |        0 |          1 |        2 |           1 |
|  41 | strider_tom          |        1 |              1 |        1 |        0 |          1 |        2 |           1 |
|  42 | J_Dymond             |        1 |              1 |        1 |        0 |          1 |        2 |           1 |
|  43 | accidentalsalmon     |        1 |              1 |        1 |        0 |          1 |        1 |           1 |
|  44 | madshjort            |        1 |              1 |        1 |        0 |          1 |        1 |           1 |
|  45 | tugboet              |        1 |              1 |        1 |        0 |          1 |        1 |           1 |
|  46 | LordOrtus            |        1 |              1 |        1 |        0 |          1 |        1 |           1 |
|  47 | GordonRamsayGhost    |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  48 | hahs95               |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  49 | lakermamba1999       |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  50 | RuleBritannia1919    |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  51 | igsey                |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
|  52 | FluidSaint           |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
|  53 | bendezhashein        |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
|  54 | T_Hr0                |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
|  55 | Finoptics            |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
|  56 | mr_grission          |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
|  57 | KingHarpoon616       |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
|  58 | chesterchugger       |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
|  59 | GuteLord-            |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
|  60 | BanjoPants74         |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
|  61 | Kindlydestroyed      |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
|  62 | BlameTibor           |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
|  63 | jjbc56               |        1 |              0 |        0 |        0 |          1 |        2 |           1 |
|  64 | Tutush               |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
|  65 | Salt-Cup-2300        |        1 |              0 |        0 |        0 |          1 |        2 |           1 |
|  66 | delegod1             |        1 |              0 |        0 |        0 |          1 |        2 |           1 |
|  67 | HandsomedanNZ        |        1 |              0 |        0 |        0 |          1 |        2 |           1 |
|  68 | Many_Background_3679 |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
|  69 | thatcrazyhorse       |        1 |              0 |        0 |        0 |          1 |        2 |           1 |
|  70 | mcsgwigga            |        1 |              0 |        0 |        0 |          1 |        2 |           1 |
|  71 | Cervix-Pounder       |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
|  72 | Positive-Sound-4972  |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
|  73 | Blackgotham-12       |        1 |              0 |        0 |        0 |          1 |        2 |           1 |
|  74 | Toast_for_President  |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
|  75 | NagromNitsuj         |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
|  76 | specifylength        |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
|  77 | saintstu             |        1 |              0 |        0 |        0 |          1 |        2 |           1 |
|  78 | infestationE15       |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
|  79 | benscott81           |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
|  80 | jeromereyes          |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
|  81 | asdaf22              |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
|  82 | Potato271            |        1 |              0 |        0 |        0 |          1 |        2 |           1 |
|  83 | Tough-Whereas1205    |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
|  84 | Adziboy              |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
|  85 | Henghast             |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
|  86 | oldredstang66        |        1 |              0 |        0 |        0 |          1 |        2 |           1 |
|  87 | magneticacorn        |        1 |              0 |        0 |        0 |          1 |        2 |           1 |
|  88 | rghsfc               |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
|  89 | Weirdo_boy02         |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
|  90 | Desperate_Low9482    |        1 |              0 |        0 |        0 |          1 |        2 |           1 |
|  91 | brandonouthouse      |        1 |              0 |        0 |        0 |          1 |        2 |           1 |
|  92 | fluffyplayery        |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
|  93 | Lucky_Strike1        |        1 |              0 |        0 |        0 |          1 |        2 |           1 |
|  94 | mdubyo               |        1 |              0 |        0 |        0 |          1 |        2 |           1 |
|  95 | kyleandrew_7         |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
|  96 | malkusm              |        1 |              0 |        0 |        0 |          1 |        2 |           1 |
|  97 | Ahegaopizza          |        1 |              0 |        0 |        0 |          1 |        2 |           1 |
|  98 | MrJoshua_182         |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
|  99 | PhilipRobertson      |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
| 100 | MetaRift             |        1 |              0 |        0 |        0 |          1 |        2 |           1 |
| 101 | JimmyRiddle707       |        1 |              0 |        0 |        0 |          1 |        2 |           1 |
| 102 | thisisclassicus      |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
| 103 | hAkonf               |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
| 104 | NorwegianSaint       |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
| 105 | alki07               |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 106 | Antidote-Killer      |        0 |              0 |        0 |        0 |          0 |        3 |           0 |
| 107 | wostmardin           |        0 |              0 |        0 |        0 |          0 |        3 |           0 |
| 108 | MAFIAxMaverick       |        0 |              0 |        0 |        0 |          0 |        2 |           0 |
| 109 | gooffking            |        0 |              0 |        0 |        0 |          0 |        2 |           0 |
| 110 | Relevant_Rev         |        0 |              0 |        0 |        0 |          0 |        3 |           0 |
| 111 | spankeycakes         |        0 |              0 |        0 |        0 |          0 |        2 |           0 |
| 112 | roberthart327        |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 113 | darave123            |        0 |              0 |        0 |        0 |          0 |        3 |           0 |
| 114 | Unlucky_Island_742   |        0 |              0 |        0 |        0 |          0 |        2 |           0 |
| 115 | redditbanana42       |        0 |              0 |        0 |        0 |          0 |        3 |           0 |
| 116 | Vsovs                |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 117 | WaltertheWobot       |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 118 | dan_3                |        0 |              0 |        0 |        0 |          0 |        2 |           0 |
| 119 | happysnappygoat      |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 120 | whowantstogo         |        0 |              0 |        0 |        0 |          0 |        3 |           0 |
| 121 | frooberts            |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 122 | gedly89              |        0 |              0 |        0 |        0 |          0 |        2 |           0 |
| 123 | K3GGY                |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 124 | Dr-Honks             |        0 |              0 |        0 |        0 |          0 |        2 |           0 |
| 125 | EntersMikers         |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 126 | Hefty-Competition297 |        0 |              0 |        0 |        0 |          0 |        3 |           0 |
| 127 | Patentlyy            |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 128 | MrRyan1320           |        0 |              0 |        0 |        0 |          0 |        2 |           0 |
| 129 | sgm94                |        0 |              0 |        0 |        0 |          0 |        3 |           0 |
| 130 | Tspecs05             |        0 |              0 |        0 |        0 |          0 |        3 |           0 |
| 131 | guillotine-jones     |        0 |              0 |        0 |        0 |          0 |        2 |           0 |
| 132 | Super-saints12       |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 133 | 3rd__i               |        0 |              0 |        0 |        0 |          0 |        3 |           0 |
| 134 | Hot_Chair_7523       |        0 |              0 |        0 |        0 |          0 |        2 |           0 |
| 135 | master_shifwho       |        0 |              0 |        0 |        0 |          0 |        2 |           0 |
| 136 | GrandmasterYoda1     |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 137 | whattodotodo8        |        0 |              0 |        0 |        0 |          0 |        3 |           0 |
| 138 | Anglo-fornian        |        0 |              0 |        0 |        0 |          0 |        2 |           0 |
| 139 | TheEggMan45          |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 140 | gongasf              |        0 |              0 |        0 |        0 |          0 |        2 |           0 |
| 141 | pctomfor             |        0 |              0 |        0 |        0 |          0 |        2 |           0 |
| 142 | jrdn1616             |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 143 | BlueInq              |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 144 | bundy554             |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 145 | BJH19                |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 146 | Whenthebeatdropolis  |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 147 | who905               |        0 |              0 |        0 |        0 |          0 |        2 |           0 |
| 148 | street--donut        |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 149 | 3ch03d               |        0 |              0 |        0 |        0 |          0 |        2 |           0 |
| 150 | Glittering-Cow-4702  |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 151 | 496e636f676e69746f   |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 152 | DrShaftmanPhD        |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 153 | baristaboy24         |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 154 | Potential-Oil-1795   |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 155 | soverign_cheese      |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 156 | Lost_Disk            |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 157 | BigTettenator        |        0 |              0 |        0 |        0 |          0 |        2 |           0 |