Schema

 - Matches:
     - MatchId: int
         - MatchWeek: int
         - HomeTeam: int
         - AwayTeam: int
         - MatchResult: pt.MatchResult
         - ThreadUrl: str
         - MatchTime: datetime (convert to UTC?)

 - Standings:
     - MatchId: int
         - UserName: str
             - Points: int

 - Predictions:
     - MatchId: int
         - UserName: str
             - Comment: str
             - CommentTime: datetime (convert to UTC?)


What if someone posts two comments?

{
    "MatchId": {
        "0": {
            "MatchWeek": 0,
            "HomeTeam": "Southampton",
            "
        }
    }
}

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from pathlib import Path
import pandas as pd
from icecream import ic

import predthread as pt
from predthread import fbref

from collections import defaultdict
from copy import deepcopy

In [3]:
root = Path(".").absolute()
print(root)

/Users/julianirwin/Projects/predthread/examples/southamton_24-25_33c895d4

In [7]:
club_names = pt.club_names(root)
api_keys = pt.api_keys(root)
match_metadata = pt.match_metadata(root, match_id=0)
matches_metadata = pt.matches_metadata(root)
matches_metadata_df = pt.matches_metadata_df(root)

# ic(club_names)
# ic(match_metadata)
# ic(matches_metadata)

In [5]:
# Of last completed match
match_id = 7

In [8]:
matches_metadata_df

,MatchWeek,HomeClub,AwayClub,HomeGoals,AwayGoals,MatchTimeUtc,ThreadUrl
0,1,Newcastle Utd,Southampton,1,0,2024-08-17T15:00:00Z,https://www.reddit.com/r/SaintsFC/comments/1et...
1,2,Southampton,Nott'ham Forest,0,1,2024-08-24T15:00:00Z,https://www.reddit.com/r/SaintsFC/comments/1ey...
2,3,Brentford,Southampton,3,1,2024-08-31T15:00:00Z,https://www.reddit.com/r/SaintsFC/comments/1f4...
3,4,Southampton,Manchester Utd,0,3,2024-09-14T12:30:00Z,https://www.reddit.com/r/SaintsFC/comments/1ff...
4,5,Southampton,Ipswich Town,1,1,2024-09-21T15:00:00Z,https://www.reddit.com/r/SaintsFC/comments/1fk...
5,6,Bournemouth,Southampton,3,1,2024-09-30T20:00:00Z,https://www.reddit.com/r/SaintsFC/comments/1fr...
6,7,Arsenal,Southampton,3,1,2024-10-05T15:00:00Z,https://www.reddit.com/r/SaintsFC/comments/1fv...
7,8,Southampton,Leicester City,2,3,2024-10-19T15:00:00Z,https://www.reddit.com/r/SaintsFC/comments/1g6...
8,9,Manchester City,Southampton,1,0,2024-10-26T15:00:00Z,https://www.reddit.com/r/SaintsFC/comments/1gb...
9,10,Southampton,Everton,1,0,2024-11-02T15:00:00Z,https://www.reddit.com/r/SaintsFC/comments/1gh...
10,11,Wolves,Southampton,,,2024-11-09T15:00:00Z,https://www.reddit.com/r/SaintsFC/comments/1gm...

In [14]:
def _next_match_id(match_metadata: dict):
    try:
        return max(map(int, match_metadata["MatchId"].keys()))
    except ValueError:
        return "0"

'9'

In [15]:
# Using matchweek, not match id
i_matchweek = 11
ic(fbref.match_metadata(i_matchweek=i_matchweek))
# pt.append_match_metadata(root, fbref.match_metadata(i_matchweek))

ic| fbref.match_metadata(i_matchweek=i_matchweek): {'AwayClub': 'Southampton',
                                                    'AwayGoals': '',
                                                    'HomeClub': 'Wolves',
                                                    'HomeGoals': '',
                                                    'MatchTimeUtc': '2024-11-09T15:00:00Z',
                                                    'MatchWeek': 11,
                                                    'ThreadUrl': ''}

TypeError: 'DataFrame' object is not callable

In [11]:
pd.set_option("display.max_rows", None)
ps = pt.download_predictions(root, match_id)
ps.sort_values(["PredictedHomeGoals", "PredictedAwayGoals"], ascending=False)
# ps

,Comment,PredictedHomeGoals,PredictedAwayGoals
UserName,,,
Antidote-Killer,11-4,11,4
nape27,3-3,3,3
master_shifwho,3-3,3,3
Holy_Shit_Balls_69,3-2,3,2
BJH19,3-2,3,2
allbarneynorubble,3-1,3,1
Relevant_Rev,3-1,3,1
whowantstogo,3-0,3,0
rghsfc,3-0 defeat,3,0
GuteLord-,3-0,3,0
Hefty-Competition297,3-0 COYR,3,0
TrumpsCheetoJizz,2-2,2,2
Bruceplanet,2-2 we score but can't hold on to the win as u...,2,2
benscott81,2-2,2,2
FalafelHalloumi,2-2,2,2
Klutzy-Put-1786,2-2 . We are not going to win a single game al...,2,2
brandonouthouse,2-2,2,2
kyleandrew_7,2-2,2,2
who905,2-1 wishful thinking for sure,2,1
redditbanana42,2-1,2,1
aredditusername69,2-1,2,1
uuuuuuuhhhhh,2-1,2,1
saintstu,2-1,2,1
NagromNitsuj,2-1 defeat. After opening the scoring.,2,1
Ok_Mix_3544,2-1,2,1
PM_ME_YOUR_MARS_BARS,2-1. It's time,2,1
JoeGordon07,2-1,2,1
496e636f676e69746f,2-1,2,1
Crazymorsejr,2-1,2,1
fartarus,2-1,2,1
gedly89,Saints 2-0,2,0
gubbyno,"2-0\n\nPointless optimism, like the top comment",2,0
JimmyRiddle707,2-0,2,0
whattodotodo8,2-0 Saints win,2,0
flailingpariah,1-5 they play similarly direct to Bournemouth ...,1,5
strider_tom,1-4,1,4
Geralt0908,1-4,1,4
BFT_022,1-3,1,3
mcsgwigga,1-3,1,3
specifylength,1-3,1,3
jjbc56,1-3,1,3
Saint_Noog,1-3. We always lose to them,1,3
Positive-Sound-4972,"1 - 3 . I am so depressed, let's get back to t...",1,3
tugboet,1-3 we lead first,1,3
teuridge,1-3,1,3
Boring_Inflation1494,1-3.,1,3
CelaenaSardothien007,1-3,1,3
Cervix-Pounder,1 - 3,1,3
Potato271,"1-3. We score first, then just capitulate.",1,3
malkusm,1-2 the most painful way you can draw it up,1,2
Intermittent-Thinker,1-2,1,2
3ch03d,1-2,1,2
gradi3nt,1-2,1,2
Zou-KaiLi,1-2,1,2
bendezhashein,1-2,1,2
Zapdosman,1-2,1,2
Patentlyy,1-2,1,2
LegitimatePass6924,1-2,1,2
ThatMoodyBstard,1-2,1,2
Nas1729,1-2,1,2
JAChambel,1-2,1,2
rigill,1-1,1,1
Tough-Whereas1205,1-1,1,1
dan_3,1-1,1,1
Hot_Chair_7523,1-1,1,1
Beardedmetalhead,1-1,1,1
lemezier,1-1,1,1
infestationE15,1-1. I can see this ending really similarly to...,1,1
Same-Temporary8468,1 - 1\n\nWe lead for most of the game then let...,1,1
dinzil02,1-1,1,1
MetaRift,1-1,1,1
slugmaniac,1-1,1,1
shontgomery,1-1,1,1
zoinks10,1-0 pointless optimism. Also how did I end up ...,1,0
madshjort,1-0 redemption,1,0
nmc1995,1-0 Saints,1,0
magneticacorn,1-0. Here we go,1,0
LordOrtus,1-0,1,0
Nixstricks,1-0 The nerviest possible game,1,0
thinlike_napkins,0-6,0,6
HandsomedanNZ,0-3\n\nI think it's time for a change.,0,3
pishkabob,0-3,0,3
spankeycakes,0-2,0,2
meteoritee,0-2,0,2
Emergency-Room-5484,0-2,0,2
halarhala,0-2,0,2
GraveRaven,0-1,0,1
TheFuzzyEucalyptus,0-1,0,1

In [12]:
pt.summarize_predictions(root, match_id)

{'TotalPredictions': 88,
 'TotalHomeWinPredictions': 31,
 'TotalAwayWinPredictions': 36,
 'TotalDrawPredictions': 21}

In [13]:
new_standings = pt.calculate_updated_standings_after(root, match_id)
new_standings

,Points,PointsGained,Streak,Exacts,Corrects,Wrongs,MaxStreak
UserName,,,,,,,
Nixstricks,11,0,0,3,2,3,7
LegitimatePass6924,10,1,5,2,4,2,5
flailingpariah,9,1,3,1,6,1,6
slugmaniac,9,0,0,2,3,3,4
Saint_Noog,8,1,7,1,5,1,7
jjbc56,8,1,7,1,5,2,7
halarhala,8,1,3,1,5,1,5
Nas1729,8,1,3,1,5,2,4
Zapdosman,8,1,2,1,5,2,5
HandsomedanNZ,7,1,5,1,4,3,5
gradi3nt,7,1,3,0,7,1,4
Emergency-Room-5484,7,1,3,0,7,1,4
shontgomery,7,0,0,2,1,4,3
FalafelHalloumi,7,0,0,1,4,3,3
MetaRift,7,0,0,1,4,3,6
malkusm,6,1,4,1,3,4,4
teuridge,6,1,3,0,6,2,3
Zou-KaiLi,6,1,3,0,6,2,3
Intermittent-Thinker,6,1,3,0,6,2,3
TheFuzzyEucalyptus,6,1,3,0,6,1,3
ThatMoodyBstard,6,1,2,0,6,1,4
fcf4,6,0,5,1,3,1,5
lemezier,6,0,0,1,3,4,3
NagromNitsuj,6,0,0,1,3,2,5
mcsgwigga,5,1,3,0,5,3,3
strider_tom,5,1,3,0,5,3,3
pishkabob,5,1,2,0,5,3,2
thinlike_napkins,5,1,2,0,5,1,3
chebalebs,5,0,1,1,2,3,3
Jpwf,5,0,1,1,2,4,3
lakermamba1999,5,0,1,1,2,1,4
benscott81,5,0,0,1,2,4,3
UtterlyRedditculous,5,0,1,0,5,1,4
meteoritee,4,1,4,0,4,0,4
Cervix-Pounder,4,1,3,0,4,1,3
specifylength,4,1,3,0,4,3,3
Boring_Inflation1494,4,1,3,0,4,1,3
JAChambel,4,1,2,0,4,1,2
KanetsuguNaoe,4,0,4,1,1,1,4
PM_ME_YOUR_MARS_BARS,4,0,0,1,1,2,4
kyleandrew_7,4,0,0,1,1,4,3
rapsin4lmao,4,0,0,1,1,1,4
Hot_Chair_7523,4,0,0,1,1,5,3
redditbanana42,4,0,0,1,1,6,3
brandonouthouse,4,0,0,1,1,4,3
FitzRoyced,4,0,2,0,4,2,2
Kindlydestroyed,4,0,2,0,4,1,2
saint-86,4,0,1,0,4,2,2
uuuuuuuhhhhh,4,0,0,0,4,4,2
fartarus,4,0,0,0,4,4,2
nape27,4,0,0,0,4,4,2
infestationE15,4,0,0,0,4,3,2
BFT_022,3,1,3,0,3,0,3
GraveRaven,3,1,3,0,3,0,3
Potato271,3,1,2,0,3,4,2
tugboet,3,1,2,0,3,4,2
CelaenaSardothien007,3,1,1,0,3,3,1
Positive-Sound-4972,3,1,1,0,3,3,1
StreetSuspicious8456,3,0,3,1,0,0,3
HOWDY__YALL,3,0,3,1,0,0,3
TheTyrantis,3,0,3,1,0,0,3
JoshHQ,3,0,3,1,0,0,3
Deadpooldan,3,0,3,1,0,0,3
SomeGuyCalledPercy,3,0,0,1,0,1,3
uKrayZ,3,0,0,1,0,1,3
Revolutionary_Cup602,3,0,2,0,3,1,2
delegod1,3,0,2,0,3,3,2
thatcrazyhorse,3,0,1,0,3,3,1
MrJoshua_182,3,0,1,0,3,3,1
RuleBritannia1919,3,0,1,0,3,1,2
hAkonf,3,0,1,0,3,2,1
hahs95,3,0,1,0,3,1,2
jackodriscol,3,0,0,0,3,2,3
magneticacorn,3,0,0,0,3,5,1
JimmyRiddle707,3,0,0,0,3,5,1
bendezhashein,2,1,2,0,2,0,2
3ch03d,2,1,2,0,2,2,2
spankeycakes,2,1,1,0,2,4,1
Zstupple,2,0,2,0,2,0,2
LovingCatholicPriest,2,0,2,0,2,1,2
BlameTibor,2,0,2,0,2,0,2
Anglo-fornian,2,0,2,0,2,2,2
HelpfulSloth14,2,0,2,0,2,0,2
mdubyo,2,0,1,0,2,2,1
Many_Background_3679,2,0,1,0,2,2,1
Tutush,2,0,1,0,2,1,1
Desperate_Low9482,2,0,1,0,2,4,1
Lucky_Strike1,2,0,1,0,2,5,1
NorwegianSaint,2,0,1,0,2,2,1
GordonRamsayGhost,2,0,1,0,2,1,1
MangerDanger1,2,0,0,0,2,4,1
jayforplay,2,0,0,0,2,2,1
accidentalsalmon,2,0,0,0,2,2,2
Relevant_Rev,2,0,0,0,2,5,1
Klutzy-Put-1786,2,0,0,0,2,2,1
saintstu,2,0,0,0,2,6,1
Tough-Whereas1205,2,0,0,0,2,4,1
Bruceplanet,2,0,0,0,2,6,1
zoinks10,2,0,0,0,2,5,1
dan_3,2,0,0,0,2,5,1
who905,2,0,0,0,2,4,2
Patentlyy,1,1,1,0,1,1,1
Geralt0908,1,1,1,0,1,1,1
igsey,1,0,1,0,1,0,1
FluidSaint,1,0,1,0,1,0,1
T_Hr0,1,0,1,0,1,0,1
Finoptics,1,0,1,0,1,0,1
mr_grission,1,0,1,0,1,0,1
KingHarpoon616,1,0,1,0,1,0,1
chesterchugger,1,0,1,0,1,0,1
3rd__i,1,0,1,0,1,3,1
baristaboy24,1,0,1,0,1,1,1
bathtub_not_beach,1,0,1,0,1,1,1
Fast-Engineer915,1,0,1,0,1,1,1
Zakedawn,1,0,1,0,1,0,1
buddyomg,1,0,1,0,1,0,1
Wafflz__,1,0,1,0,1,0,1
BevvyTime,1,0,1,0,1,0,1
galaxygalaxy777,1,0,1,0,1,0,1
Squm9,1,0,1,0,1,1,1
Captain_Obvious_x,1,0,1,0,1,1,1
Fatty4forks,1,0,1,0,1,0,1
wostmardin,1,0,1,0,1,3,1
Tspecs05,1,0,1,0,1,6,1
exhaleair,1,0,1,0,1,3,1
kempston_joystick,1,0,1,0,1,2,1
rabbitradar,1,0,1,0,1,2,1
TouristDramatic8295,1,0,1,0,1,1,1
kevmccartney,1,0,1,0,1,1,1
SoggyMattress2,1,0,1,0,1,0,1
boondocksaint08,1,0,1,0,1,0,1
OpScreechingHalt,1,0,1,0,1,0,1
Financial-Glass5693,1,0,1,0,1,0,1
Educational_Ad288,1,0,1,0,1,0,1
No_Amphibian6382,1,0,1,0,1,0,1
ThermoWizz,1,0,1,0,1,0,1
GuyInWessex,1,0,1,0,1,0,1
Likunandi,1,0,1,0,1,0,1
Salt-Cup-2300,1,0,0,0,1,3,1
Blackgotham-12,1,0,0,0,1,2,1
Toast_for_President,1,0,0,0,1,1,1
jeromereyes,1,0,0,0,1,1,1
asdaf22,1,0,0,0,1,1,1
Adziboy,1,0,0,0,1,1,1
Henghast,1,0,0,0,1,1,1
oldredstang66,1,0,0,0,1,5,1
rghsfc,1,0,0,0,1,4,1
Weirdo_boy02,1,0,0,0,1,3,1
fluffyplayery,1,0,0,0,1,1,1
Ahegaopizza,1,0,0,0,1,2,1
PhilipRobertson,1,0,0,0,1,2,1
thisisclassicus,1,0,0,0,1,2,1
GuteLord-,1,0,0,0,1,2,1
BanjoPants74,1,0,0,0,1,1,1
J_Dymond,1,0,0,0,1,3,1
madshjort,1,0,0,0,1,3,1
allbarneynorubble,1,0,0,0,1,3,1
LordOrtus,1,0,0,0,1,3,1
DeadSpaceLover,1,0,0,0,1,2,1
Bayne7096,1,0,0,0,1,3,1
BJH19,1,0,0,0,1,4,1
gedly89,1,0,0,0,1,4,1
496e636f676e69746f,1,0,0,0,1,5,1
aredditusername69,1,0,0,0,1,3,1
Holy_Shit_Balls_69,1,0,0,0,1,4,1
TrumpsCheetoJizz,1,0,0,0,1,1,1
Beardedmetalhead,1,0,0,0,1,1,1
alki07,0,0,0,0,0,1,0
Antidote-Killer,0,0,0,0,0,6,0
MAFIAxMaverick,0,0,0,0,0,4,0
gooffking,0,0,0,0,0,2,0
roberthart327,0,0,0,0,0,1,0
darave123,0,0,0,0,0,3,0
Unlucky_Island_742,0,0,0,0,0,2,0
Vsovs,0,0,0,0,0,1,0
WaltertheWobot,0,0,0,0,0,2,0
happysnappygoat,0,0,0,0,0,1,0
whowantstogo,0,0,0,0,0,7,0
frooberts,0,0,0,0,0,1,0
K3GGY,0,0,0,0,0,1,0
Dr-Honks,0,0,0,0,0,2,0
EntersMikers,0,0,0,0,0,1,0
Hefty-Competition297,0,0,0,0,0,8,0
MrRyan1320,0,0,0,0,0,2,0
sgm94,0,0,0,0,0,3,0
guillotine-jones,0,0,0,0,0,2,0
Super-saints12,0,0,0,0,0,1,0
master_shifwho,0,0,0,0,0,3,0
GrandmasterYoda1,0,0,0,0,0,2,0
whattodotodo8,0,0,0,0,0,8,0
TheEggMan45,0,0,0,0,0,1,0
gongasf,0,0,0,0,0,2,0
pctomfor,0,0,0,0,0,2,0
jrdn1616,0,0,0,0,0,2,0
BlueInq,0,0,0,0,0,2,0
bundy554,0,0,0,0,0,1,0
Whenthebeatdropolis,0,0,0,0,0,1,0
street--donut,0,0,0,0,0,1,0
Glittering-Cow-4702,0,0,0,0,0,1,0
DrShaftmanPhD,0,0,0,0,0,3,0
Potential-Oil-1795,0,0,0,0,0,1,0
soverign_cheese,0,0,0,0,0,1,0
Lost_Disk,0,0,0,0,0,3,0
BigTettenator,0,0,0,0,0,2,0
West_Equivalent7997,0,0,0,0,0,1,0
MonarchyBoner,0,0,0,0,0,1,0
Alina2017,0,0,0,0,0,1,0
Cormac419,0,0,0,0,0,1,0
gubbyno,0,0,0,0,0,3,0
King_Lamb,0,0,0,0,0,1,0
PunnyIsNotFunny,0,0,0,0,0,1,0
weatherghost,0,0,0,0,0,1,0
Nervous_Jaguar_2826,0,0,0,0,0,1,0
Weary_Initiative5582,0,0,0,0,0,3,0
throwaway1throwawa,0,0,0,0,0,1,0
jonnyhoots,0,0,0,0,0,2,0
JoeBiggzDC,0,0,0,0,0,1,0
LiveFree-603,0,0,0,0,0,1,0
TheHatThatTalks,0,0,0,0,0,1,0
Top_Dirt2557,0,0,0,0,0,1,0
Notional-,0,0,0,0,0,1,0
BrandonPol,0,0,0,0,0,1,0
Singh255,0,0,0,0,0,1,0
King_PieNan,0,0,0,0,0,1,0
Ok_Mix_3544,0,0,0,0,0,2,0
matt_rev,0,0,0,0,0,3,0
Mr_Yellow_Trousers,0,0,0,0,0,3,0
Magmar18,0,0,0,0,0,1,0
neil2252,0,0,0,0,0,1,0
No_Wrap_9979,0,0,0,0,0,1,0
istarisaints,0,0,0,0,0,1,0
FromTheEdgeOfTheDeep,0,0,0,0,0,2,0
Jamez_XIX,0,0,0,0,0,1,0
Evening-Tart3067,0,0,0,0,0,1,0
mbridge2610,0,0,0,0,0,1,0
senorbellend17,0,0,0,0,0,1,0
No_Pound5513,0,0,0,0,0,1,0
HorusHeresay,0,0,0,0,0,1,0
GreedoVision,0,0,0,0,0,1,0
TheSpitfires,0,0,0,0,0,1,0
fl0ralp,0,0,0,0,0,1,0
Adventurous_Bass_673,0,0,0,0,0,1,0
YourWeekendDad,0,0,0,0,0,1,0
rigill,0,0,0,0,0,1,0
nmc1995,0,0,0,0,0,1,0
Same-Temporary8468,0,0,0,0,0,1,0
dinzil02,0,0,0,0,0,1,0
JoeGordon07,0,0,0,0,0,1,0
Crazymorsejr,0,0,0,0,0,1,0

In [14]:
print(new_standings.reset_index().to_markdown())

|     | UserName             |   Points |   PointsGained |   Streak |   Exacts |   Corrects |   Wrongs |   MaxStreak |
|----:|:---------------------|---------:|---------------:|---------:|---------:|-----------:|---------:|------------:|
|   0 | Nixstricks           |       11 |              0 |        0 |        3 |          2 |        3 |           7 |
|   1 | LegitimatePass6924   |       10 |              1 |        5 |        2 |          4 |        2 |           5 |
|   2 | flailingpariah       |        9 |              1 |        3 |        1 |          6 |        1 |           6 |
|   3 | slugmaniac           |        9 |              0 |        0 |        2 |          3 |        3 |           4 |
|   4 | Saint_Noog           |        8 |              1 |        7 |        1 |          5 |        1 |           7 |
|   5 | jjbc56               |        8 |              1 |        7 |        1 |          5 |        2 |           7 |
|   6 | halarhala            |        8 |              1 |        3 |        1 |          5 |        1 |           5 |
|   7 | Nas1729              |        8 |              1 |        3 |        1 |          5 |        2 |           4 |
|   8 | Zapdosman            |        8 |              1 |        2 |        1 |          5 |        2 |           5 |
|   9 | HandsomedanNZ        |        7 |              1 |        5 |        1 |          4 |        3 |           5 |
|  10 | gradi3nt             |        7 |              1 |        3 |        0 |          7 |        1 |           4 |
|  11 | Emergency-Room-5484  |        7 |              1 |        3 |        0 |          7 |        1 |           4 |
|  12 | shontgomery          |        7 |              0 |        0 |        2 |          1 |        4 |           3 |
|  13 | FalafelHalloumi      |        7 |              0 |        0 |        1 |          4 |        3 |           3 |
|  14 | MetaRift             |        7 |              0 |        0 |        1 |          4 |        3 |           6 |
|  15 | malkusm              |        6 |              1 |        4 |        1 |          3 |        4 |           4 |
|  16 | teuridge             |        6 |              1 |        3 |        0 |          6 |        2 |           3 |
|  17 | Zou-KaiLi            |        6 |              1 |        3 |        0 |          6 |        2 |           3 |
|  18 | Intermittent-Thinker |        6 |              1 |        3 |        0 |          6 |        2 |           3 |
|  19 | TheFuzzyEucalyptus   |        6 |              1 |        3 |        0 |          6 |        1 |           3 |
|  20 | ThatMoodyBstard      |        6 |              1 |        2 |        0 |          6 |        1 |           4 |
|  21 | fcf4                 |        6 |              0 |        5 |        1 |          3 |        1 |           5 |
|  22 | lemezier             |        6 |              0 |        0 |        1 |          3 |        4 |           3 |
|  23 | NagromNitsuj         |        6 |              0 |        0 |        1 |          3 |        2 |           5 |
|  24 | mcsgwigga            |        5 |              1 |        3 |        0 |          5 |        3 |           3 |
|  25 | strider_tom          |        5 |              1 |        3 |        0 |          5 |        3 |           3 |
|  26 | pishkabob            |        5 |              1 |        2 |        0 |          5 |        3 |           2 |
|  27 | thinlike_napkins     |        5 |              1 |        2 |        0 |          5 |        1 |           3 |
|  28 | chebalebs            |        5 |              0 |        1 |        1 |          2 |        3 |           3 |
|  29 | Jpwf                 |        5 |              0 |        1 |        1 |          2 |        4 |           3 |
|  30 | lakermamba1999       |        5 |              0 |        1 |        1 |          2 |        1 |           4 |
|  31 | benscott81           |        5 |              0 |        0 |        1 |          2 |        4 |           3 |
|  32 | UtterlyRedditculous  |        5 |              0 |        1 |        0 |          5 |        1 |           4 |
|  33 | meteoritee           |        4 |              1 |        4 |        0 |          4 |        0 |           4 |
|  34 | Cervix-Pounder       |        4 |              1 |        3 |        0 |          4 |        1 |           3 |
|  35 | specifylength        |        4 |              1 |        3 |        0 |          4 |        3 |           3 |
|  36 | Boring_Inflation1494 |        4 |              1 |        3 |        0 |          4 |        1 |           3 |
|  37 | JAChambel            |        4 |              1 |        2 |        0 |          4 |        1 |           2 |
|  38 | KanetsuguNaoe        |        4 |              0 |        4 |        1 |          1 |        1 |           4 |
|  39 | PM_ME_YOUR_MARS_BARS |        4 |              0 |        0 |        1 |          1 |        2 |           4 |
|  40 | kyleandrew_7         |        4 |              0 |        0 |        1 |          1 |        4 |           3 |
|  41 | rapsin4lmao          |        4 |              0 |        0 |        1 |          1 |        1 |           4 |
|  42 | Hot_Chair_7523       |        4 |              0 |        0 |        1 |          1 |        5 |           3 |
|  43 | redditbanana42       |        4 |              0 |        0 |        1 |          1 |        6 |           3 |
|  44 | brandonouthouse      |        4 |              0 |        0 |        1 |          1 |        4 |           3 |
|  45 | FitzRoyced           |        4 |              0 |        2 |        0 |          4 |        2 |           2 |
|  46 | Kindlydestroyed      |        4 |              0 |        2 |        0 |          4 |        1 |           2 |
|  47 | saint-86             |        4 |              0 |        1 |        0 |          4 |        2 |           2 |
|  48 | uuuuuuuhhhhh         |        4 |              0 |        0 |        0 |          4 |        4 |           2 |
|  49 | fartarus             |        4 |              0 |        0 |        0 |          4 |        4 |           2 |
|  50 | nape27               |        4 |              0 |        0 |        0 |          4 |        4 |           2 |
|  51 | infestationE15       |        4 |              0 |        0 |        0 |          4 |        3 |           2 |
|  52 | BFT_022              |        3 |              1 |        3 |        0 |          3 |        0 |           3 |
|  53 | GraveRaven           |        3 |              1 |        3 |        0 |          3 |        0 |           3 |
|  54 | Potato271            |        3 |              1 |        2 |        0 |          3 |        4 |           2 |
|  55 | tugboet              |        3 |              1 |        2 |        0 |          3 |        4 |           2 |
|  56 | CelaenaSardothien007 |        3 |              1 |        1 |        0 |          3 |        3 |           1 |
|  57 | Positive-Sound-4972  |        3 |              1 |        1 |        0 |          3 |        3 |           1 |
|  58 | StreetSuspicious8456 |        3 |              0 |        3 |        1 |          0 |        0 |           3 |
|  59 | HOWDY__YALL          |        3 |              0 |        3 |        1 |          0 |        0 |           3 |
|  60 | TheTyrantis          |        3 |              0 |        3 |        1 |          0 |        0 |           3 |
|  61 | JoshHQ               |        3 |              0 |        3 |        1 |          0 |        0 |           3 |
|  62 | Deadpooldan          |        3 |              0 |        3 |        1 |          0 |        0 |           3 |
|  63 | SomeGuyCalledPercy   |        3 |              0 |        0 |        1 |          0 |        1 |           3 |
|  64 | uKrayZ               |        3 |              0 |        0 |        1 |          0 |        1 |           3 |
|  65 | Revolutionary_Cup602 |        3 |              0 |        2 |        0 |          3 |        1 |           2 |
|  66 | delegod1             |        3 |              0 |        2 |        0 |          3 |        3 |           2 |
|  67 | thatcrazyhorse       |        3 |              0 |        1 |        0 |          3 |        3 |           1 |
|  68 | MrJoshua_182         |        3 |              0 |        1 |        0 |          3 |        3 |           1 |
|  69 | RuleBritannia1919    |        3 |              0 |        1 |        0 |          3 |        1 |           2 |
|  70 | hAkonf               |        3 |              0 |        1 |        0 |          3 |        2 |           1 |
|  71 | hahs95               |        3 |              0 |        1 |        0 |          3 |        1 |           2 |
|  72 | jackodriscol         |        3 |              0 |        0 |        0 |          3 |        2 |           3 |
|  73 | magneticacorn        |        3 |              0 |        0 |        0 |          3 |        5 |           1 |
|  74 | JimmyRiddle707       |        3 |              0 |        0 |        0 |          3 |        5 |           1 |
|  75 | bendezhashein        |        2 |              1 |        2 |        0 |          2 |        0 |           2 |
|  76 | 3ch03d               |        2 |              1 |        2 |        0 |          2 |        2 |           2 |
|  77 | spankeycakes         |        2 |              1 |        1 |        0 |          2 |        4 |           1 |
|  78 | Zstupple             |        2 |              0 |        2 |        0 |          2 |        0 |           2 |
|  79 | LovingCatholicPriest |        2 |              0 |        2 |        0 |          2 |        1 |           2 |
|  80 | BlameTibor           |        2 |              0 |        2 |        0 |          2 |        0 |           2 |
|  81 | Anglo-fornian        |        2 |              0 |        2 |        0 |          2 |        2 |           2 |
|  82 | HelpfulSloth14       |        2 |              0 |        2 |        0 |          2 |        0 |           2 |
|  83 | mdubyo               |        2 |              0 |        1 |        0 |          2 |        2 |           1 |
|  84 | Many_Background_3679 |        2 |              0 |        1 |        0 |          2 |        2 |           1 |
|  85 | Tutush               |        2 |              0 |        1 |        0 |          2 |        1 |           1 |
|  86 | Desperate_Low9482    |        2 |              0 |        1 |        0 |          2 |        4 |           1 |
|  87 | Lucky_Strike1        |        2 |              0 |        1 |        0 |          2 |        5 |           1 |
|  88 | NorwegianSaint       |        2 |              0 |        1 |        0 |          2 |        2 |           1 |
|  89 | GordonRamsayGhost    |        2 |              0 |        1 |        0 |          2 |        1 |           1 |
|  90 | MangerDanger1        |        2 |              0 |        0 |        0 |          2 |        4 |           1 |
|  91 | jayforplay           |        2 |              0 |        0 |        0 |          2 |        2 |           1 |
|  92 | accidentalsalmon     |        2 |              0 |        0 |        0 |          2 |        2 |           2 |
|  93 | Relevant_Rev         |        2 |              0 |        0 |        0 |          2 |        5 |           1 |
|  94 | Klutzy-Put-1786      |        2 |              0 |        0 |        0 |          2 |        2 |           1 |
|  95 | saintstu             |        2 |              0 |        0 |        0 |          2 |        6 |           1 |
|  96 | Tough-Whereas1205    |        2 |              0 |        0 |        0 |          2 |        4 |           1 |
|  97 | Bruceplanet          |        2 |              0 |        0 |        0 |          2 |        6 |           1 |
|  98 | zoinks10             |        2 |              0 |        0 |        0 |          2 |        5 |           1 |
|  99 | dan_3                |        2 |              0 |        0 |        0 |          2 |        5 |           1 |
| 100 | who905               |        2 |              0 |        0 |        0 |          2 |        4 |           2 |
| 101 | Patentlyy            |        1 |              1 |        1 |        0 |          1 |        1 |           1 |
| 102 | Geralt0908           |        1 |              1 |        1 |        0 |          1 |        1 |           1 |
| 103 | igsey                |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 104 | FluidSaint           |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 105 | T_Hr0                |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 106 | Finoptics            |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 107 | mr_grission          |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 108 | KingHarpoon616       |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 109 | chesterchugger       |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 110 | 3rd__i               |        1 |              0 |        1 |        0 |          1 |        3 |           1 |
| 111 | baristaboy24         |        1 |              0 |        1 |        0 |          1 |        1 |           1 |
| 112 | bathtub_not_beach    |        1 |              0 |        1 |        0 |          1 |        1 |           1 |
| 113 | Fast-Engineer915     |        1 |              0 |        1 |        0 |          1 |        1 |           1 |
| 114 | Zakedawn             |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 115 | buddyomg             |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 116 | Wafflz__             |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 117 | BevvyTime            |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 118 | galaxygalaxy777      |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 119 | Squm9                |        1 |              0 |        1 |        0 |          1 |        1 |           1 |
| 120 | Captain_Obvious_x    |        1 |              0 |        1 |        0 |          1 |        1 |           1 |
| 121 | Fatty4forks          |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 122 | wostmardin           |        1 |              0 |        1 |        0 |          1 |        3 |           1 |
| 123 | Tspecs05             |        1 |              0 |        1 |        0 |          1 |        6 |           1 |
| 124 | exhaleair            |        1 |              0 |        1 |        0 |          1 |        3 |           1 |
| 125 | kempston_joystick    |        1 |              0 |        1 |        0 |          1 |        2 |           1 |
| 126 | rabbitradar          |        1 |              0 |        1 |        0 |          1 |        2 |           1 |
| 127 | TouristDramatic8295  |        1 |              0 |        1 |        0 |          1 |        1 |           1 |
| 128 | kevmccartney         |        1 |              0 |        1 |        0 |          1 |        1 |           1 |
| 129 | SoggyMattress2       |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 130 | boondocksaint08      |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 131 | OpScreechingHalt     |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 132 | Financial-Glass5693  |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 133 | Educational_Ad288    |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 134 | No_Amphibian6382     |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 135 | ThermoWizz           |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 136 | GuyInWessex          |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 137 | Likunandi            |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 138 | Salt-Cup-2300        |        1 |              0 |        0 |        0 |          1 |        3 |           1 |
| 139 | Blackgotham-12       |        1 |              0 |        0 |        0 |          1 |        2 |           1 |
| 140 | Toast_for_President  |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
| 141 | jeromereyes          |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
| 142 | asdaf22              |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
| 143 | Adziboy              |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
| 144 | Henghast             |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
| 145 | oldredstang66        |        1 |              0 |        0 |        0 |          1 |        5 |           1 |
| 146 | rghsfc               |        1 |              0 |        0 |        0 |          1 |        4 |           1 |
| 147 | Weirdo_boy02         |        1 |              0 |        0 |        0 |          1 |        3 |           1 |
| 148 | fluffyplayery        |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
| 149 | Ahegaopizza          |        1 |              0 |        0 |        0 |          1 |        2 |           1 |
| 150 | PhilipRobertson      |        1 |              0 |        0 |        0 |          1 |        2 |           1 |
| 151 | thisisclassicus      |        1 |              0 |        0 |        0 |          1 |        2 |           1 |
| 152 | GuteLord-            |        1 |              0 |        0 |        0 |          1 |        2 |           1 |
| 153 | BanjoPants74         |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
| 154 | J_Dymond             |        1 |              0 |        0 |        0 |          1 |        3 |           1 |
| 155 | madshjort            |        1 |              0 |        0 |        0 |          1 |        3 |           1 |
| 156 | allbarneynorubble    |        1 |              0 |        0 |        0 |          1 |        3 |           1 |
| 157 | LordOrtus            |        1 |              0 |        0 |        0 |          1 |        3 |           1 |
| 158 | DeadSpaceLover       |        1 |              0 |        0 |        0 |          1 |        2 |           1 |
| 159 | Bayne7096            |        1 |              0 |        0 |        0 |          1 |        3 |           1 |
| 160 | BJH19                |        1 |              0 |        0 |        0 |          1 |        4 |           1 |
| 161 | gedly89              |        1 |              0 |        0 |        0 |          1 |        4 |           1 |
| 162 | 496e636f676e69746f   |        1 |              0 |        0 |        0 |          1 |        5 |           1 |
| 163 | aredditusername69    |        1 |              0 |        0 |        0 |          1 |        3 |           1 |
| 164 | Holy_Shit_Balls_69   |        1 |              0 |        0 |        0 |          1 |        4 |           1 |
| 165 | TrumpsCheetoJizz     |        1 |              0 |        0 |        0 |          1 |        1 |           1 |

In [ ]:
predictions = pt.load_predictions(root, match_id)
old_standings = pt.load_standings_after(root, match_id - 1)
new_standings_p = pt.load_standings_after(root, match_id)
new_standings_p = new_standings.rename(columns=lambda x: x + "*")
predictions.join(old_standings, new_standings_p)

In [15]:
pt.summarize_standings_after(root, match_id)

{'TotalExacts': 0, 'TotalCorrects': 36}

# Post Template

## Todo

 - Add callouts for exacts and streaks

In [19]:
m_next = pt.match_metadata(root, match_id+1)
m_last = pt.match_metadata(root, match_id)

s_pred = pt.summarize_predictions(root, match_id - 1)
s_stand = pt.summarize_standings_after(root, match_id-1)

print(f"""
# Prediction Thread Match {match_id + 2}: {m_next["HomeClub"]} vs {m_next["AwayClub"]}

# Home - Away Format

 - Home: {m_next["HomeClub"]}
 - Away: {m_next["AwayClub"]}

# Game Rules

 - Post a top level comment in this thread at least one hour before kickoff, before lineups are posted.
 - Follow the format of this example comment: "0 - 3. Banter goes here."
 - Comment format must be "[Home Score] - [Away Score]. [Optional explanation, detailed prediction, or general shit talking here.]"
 - Scoring:
    - **3 points** for an exactly correct prediction.
    - **1 points** for a correct result.
    - **0 points** for an incorrect result.
- DM me with any problems, questions, comments.

# Summary of Last Match ({m_last["HomeClub"]} - {m_last["AwayClub"]})

{m_last["ThreadUrl"]}

 - Total Predictions: {s_pred["TotalPredictions"]}
 - Predicted Home Wins: {s_pred["TotalHomeWinPredictions"]} 
 - Predicted Away Wins: {s_pred["TotalAwayWinPredictions"]} 
 - Predicted Draws: {s_pred["TotalDrawPredictions"]}
 - Exacts: {s_stand["TotalExacts"]}
 - Corrects: {s_stand["TotalCorrects"]} 

# Standings
{new_standings.reset_index().to_markdown()}
""")

# Prediction Thread Match 9: Manchester City vs Southampton

# Home - Away Format

 - Home: Manchester City
 - Away: Southampton

# Game Rules

 - Post a top level comment in this thread at least one hour before kickoff, before lineups are posted.
 - Follow the format of this example comment: "0 - 3. Banter goes here."
 - Comment format must be "[Home Score] - [Away Score]. [Optional explanation, detailed prediction, or general shit talking here.]"
 - Scoring:
    - **3 points** for an exactly correct prediction.
    - **1 points** for a correct result.
    - **0 points** for an incorrect result.
- DM me with any problems, questions, comments.

# Summary of Last Match (Southampton - Leicester City)

https://www.reddit.com/r/SaintsFC/comments/1g64wgc/prediction_thread_match_8_southampton_vs/

 - Total Predictions: 108
 - Predicted Home Wins: 97
 - Predicted Away Wins: 9
 - Predicted Draws: 2
 - Exacts: 3
 - Corrects: 94

# Standings
|     | UserName             |   Points |   PointsGained |   Streak |   Exacts |   Corrects |   Wrongs |   MaxStreak |
|----:|:---------------------|---------:|---------------:|---------:|---------:|-----------:|---------:|------------:|
|   0 | Nixstricks           |       11 |              0 |        0 |        3 |          2 |        3 |           7 |
|   1 | LegitimatePass6924   |       10 |              1 |        5 |        2 |          4 |        2 |           5 |
|   2 | flailingpariah       |        9 |              1 |        3 |        1 |          6 |        1 |           6 |
|   3 | slugmaniac           |        9 |              0 |        0 |        2 |          3 |        3 |           4 |
|   4 | Saint_Noog           |        8 |              1 |        7 |        1 |          5 |        1 |           7 |
|   5 | jjbc56               |        8 |              1 |        7 |        1 |          5 |        2 |           7 |
|   6 | halarhala            |        8 |              1 |        3 |        1 |          5 |        1 |           5 |
|   7 | Nas1729              |        8 |              1 |        3 |        1 |          5 |        2 |           4 |
|   8 | Zapdosman            |        8 |              1 |        2 |        1 |          5 |        2 |           5 |
|   9 | HandsomedanNZ        |        7 |              1 |        5 |        1 |          4 |        3 |           5 |
|  10 | gradi3nt             |        7 |              1 |        3 |        0 |          7 |        1 |           4 |
|  11 | Emergency-Room-5484  |        7 |              1 |        3 |        0 |          7 |        1 |           4 |
|  12 | shontgomery          |        7 |              0 |        0 |        2 |          1 |        4 |           3 |
|  13 | FalafelHalloumi      |        7 |              0 |        0 |        1 |          4 |        3 |           3 |
|  14 | MetaRift             |        7 |              0 |        0 |        1 |          4 |        3 |           6 |
|  15 | malkusm              |        6 |              1 |        4 |        1 |          3 |        4 |           4 |
|  16 | teuridge             |        6 |              1 |        3 |        0 |          6 |        2 |           3 |
|  17 | Zou-KaiLi            |        6 |              1 |        3 |        0 |          6 |        2 |           3 |
|  18 | Intermittent-Thinker |        6 |              1 |        3 |        0 |          6 |        2 |           3 |
|  19 | TheFuzzyEucalyptus   |        6 |              1 |        3 |        0 |          6 |        1 |           3 |
|  20 | ThatMoodyBstard      |        6 |              1 |        2 |        0 |          6 |        1 |           4 |
|  21 | fcf4                 |        6 |              0 |        5 |        1 |          3 |        1 |           5 |
|  22 | lemezier             |        6 |              0 |        0 |        1 |          3 |        4 |           3 |
|  23 | NagromNitsuj         |        6 |              0 |        0 |        1 |          3 |        2 |           5 |
|  24 | mcsgwigga            |        5 |              1 |        3 |        0 |          5 |        3 |           3 |
|  25 | strider_tom          |        5 |              1 |        3 |        0 |          5 |        3 |           3 |
|  26 | pishkabob            |        5 |              1 |        2 |        0 |          5 |        3 |           2 |
|  27 | thinlike_napkins     |        5 |              1 |        2 |        0 |          5 |        1 |           3 |
|  28 | chebalebs            |        5 |              0 |        1 |        1 |          2 |        3 |           3 |
|  29 | Jpwf                 |        5 |              0 |        1 |        1 |          2 |        4 |           3 |
|  30 | lakermamba1999       |        5 |              0 |        1 |        1 |          2 |        1 |           4 |
|  31 | benscott81           |        5 |              0 |        0 |        1 |          2 |        4 |           3 |
|  32 | UtterlyRedditculous  |        5 |              0 |        1 |        0 |          5 |        1 |           4 |
|  33 | meteoritee           |        4 |              1 |        4 |        0 |          4 |        0 |           4 |
|  34 | Cervix-Pounder       |        4 |              1 |        3 |        0 |          4 |        1 |           3 |
|  35 | specifylength        |        4 |              1 |        3 |        0 |          4 |        3 |           3 |
|  36 | Boring_Inflation1494 |        4 |              1 |        3 |        0 |          4 |        1 |           3 |
|  37 | JAChambel            |        4 |              1 |        2 |        0 |          4 |        1 |           2 |
|  38 | KanetsuguNaoe        |        4 |              0 |        4 |        1 |          1 |        1 |           4 |
|  39 | PM_ME_YOUR_MARS_BARS |        4 |              0 |        0 |        1 |          1 |        2 |           4 |
|  40 | kyleandrew_7         |        4 |              0 |        0 |        1 |          1 |        4 |           3 |
|  41 | rapsin4lmao          |        4 |              0 |        0 |        1 |          1 |        1 |           4 |
|  42 | Hot_Chair_7523       |        4 |              0 |        0 |        1 |          1 |        5 |           3 |
|  43 | redditbanana42       |        4 |              0 |        0 |        1 |          1 |        6 |           3 |
|  44 | brandonouthouse      |        4 |              0 |        0 |        1 |          1 |        4 |           3 |
|  45 | FitzRoyced           |        4 |              0 |        2 |        0 |          4 |        2 |           2 |
|  46 | Kindlydestroyed      |        4 |              0 |        2 |        0 |          4 |        1 |           2 |
|  47 | saint-86             |        4 |              0 |        1 |        0 |          4 |        2 |           2 |
|  48 | uuuuuuuhhhhh         |        4 |              0 |        0 |        0 |          4 |        4 |           2 |
|  49 | fartarus             |        4 |              0 |        0 |        0 |          4 |        4 |           2 |
|  50 | nape27               |        4 |              0 |        0 |        0 |          4 |        4 |           2 |
|  51 | infestationE15       |        4 |              0 |        0 |        0 |          4 |        3 |           2 |
|  52 | BFT_022              |        3 |              1 |        3 |        0 |          3 |        0 |           3 |
|  53 | GraveRaven           |        3 |              1 |        3 |        0 |          3 |        0 |           3 |
|  54 | Potato271            |        3 |              1 |        2 |        0 |          3 |        4 |           2 |
|  55 | tugboet              |        3 |              1 |        2 |        0 |          3 |        4 |           2 |
|  56 | CelaenaSardothien007 |        3 |              1 |        1 |        0 |          3 |        3 |           1 |
|  57 | Positive-Sound-4972  |        3 |              1 |        1 |        0 |          3 |        3 |           1 |
|  58 | StreetSuspicious8456 |        3 |              0 |        3 |        1 |          0 |        0 |           3 |
|  59 | HOWDY__YALL          |        3 |              0 |        3 |        1 |          0 |        0 |           3 |
|  60 | TheTyrantis          |        3 |              0 |        3 |        1 |          0 |        0 |           3 |
|  61 | JoshHQ               |        3 |              0 |        3 |        1 |          0 |        0 |           3 |
|  62 | Deadpooldan          |        3 |              0 |        3 |        1 |          0 |        0 |           3 |
|  63 | SomeGuyCalledPercy   |        3 |              0 |        0 |        1 |          0 |        1 |           3 |
|  64 | uKrayZ               |        3 |              0 |        0 |        1 |          0 |        1 |           3 |
|  65 | Revolutionary_Cup602 |        3 |              0 |        2 |        0 |          3 |        1 |           2 |
|  66 | delegod1             |        3 |              0 |        2 |        0 |          3 |        3 |           2 |
|  67 | thatcrazyhorse       |        3 |              0 |        1 |        0 |          3 |        3 |           1 |
|  68 | MrJoshua_182         |        3 |              0 |        1 |        0 |          3 |        3 |           1 |
|  69 | RuleBritannia1919    |        3 |              0 |        1 |        0 |          3 |        1 |           2 |
|  70 | hAkonf               |        3 |              0 |        1 |        0 |          3 |        2 |           1 |
|  71 | hahs95               |        3 |              0 |        1 |        0 |          3 |        1 |           2 |
|  72 | jackodriscol         |        3 |              0 |        0 |        0 |          3 |        2 |           3 |
|  73 | magneticacorn        |        3 |              0 |        0 |        0 |          3 |        5 |           1 |
|  74 | JimmyRiddle707       |        3 |              0 |        0 |        0 |          3 |        5 |           1 |
|  75 | bendezhashein        |        2 |              1 |        2 |        0 |          2 |        0 |           2 |
|  76 | 3ch03d               |        2 |              1 |        2 |        0 |          2 |        2 |           2 |
|  77 | spankeycakes         |        2 |              1 |        1 |        0 |          2 |        4 |           1 |
|  78 | Zstupple             |        2 |              0 |        2 |        0 |          2 |        0 |           2 |
|  79 | LovingCatholicPriest |        2 |              0 |        2 |        0 |          2 |        1 |           2 |
|  80 | BlameTibor           |        2 |              0 |        2 |        0 |          2 |        0 |           2 |
|  81 | Anglo-fornian        |        2 |              0 |        2 |        0 |          2 |        2 |           2 |
|  82 | HelpfulSloth14       |        2 |              0 |        2 |        0 |          2 |        0 |           2 |
|  83 | mdubyo               |        2 |              0 |        1 |        0 |          2 |        2 |           1 |
|  84 | Many_Background_3679 |        2 |              0 |        1 |        0 |          2 |        2 |           1 |
|  85 | Tutush               |        2 |              0 |        1 |        0 |          2 |        1 |           1 |
|  86 | Desperate_Low9482    |        2 |              0 |        1 |        0 |          2 |        4 |           1 |
|  87 | Lucky_Strike1        |        2 |              0 |        1 |        0 |          2 |        5 |           1 |
|  88 | NorwegianSaint       |        2 |              0 |        1 |        0 |          2 |        2 |           1 |
|  89 | GordonRamsayGhost    |        2 |              0 |        1 |        0 |          2 |        1 |           1 |
|  90 | MangerDanger1        |        2 |              0 |        0 |        0 |          2 |        4 |           1 |
|  91 | jayforplay           |        2 |              0 |        0 |        0 |          2 |        2 |           1 |
|  92 | accidentalsalmon     |        2 |              0 |        0 |        0 |          2 |        2 |           2 |
|  93 | Relevant_Rev         |        2 |              0 |        0 |        0 |          2 |        5 |           1 |
|  94 | Klutzy-Put-1786      |        2 |              0 |        0 |        0 |          2 |        2 |           1 |
|  95 | saintstu             |        2 |              0 |        0 |        0 |          2 |        6 |           1 |
|  96 | Tough-Whereas1205    |        2 |              0 |        0 |        0 |          2 |        4 |           1 |
|  97 | Bruceplanet          |        2 |              0 |        0 |        0 |          2 |        6 |           1 |
|  98 | zoinks10             |        2 |              0 |        0 |        0 |          2 |        5 |           1 |
|  99 | dan_3                |        2 |              0 |        0 |        0 |          2 |        5 |           1 |
| 100 | who905               |        2 |              0 |        0 |        0 |          2 |        4 |           2 |
| 101 | Patentlyy            |        1 |              1 |        1 |        0 |          1 |        1 |           1 |
| 102 | Geralt0908           |        1 |              1 |        1 |        0 |          1 |        1 |           1 |
| 103 | igsey                |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 104 | FluidSaint           |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 105 | T_Hr0                |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 106 | Finoptics            |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 107 | mr_grission          |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 108 | KingHarpoon616       |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 109 | chesterchugger       |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 110 | 3rd__i               |        1 |              0 |        1 |        0 |          1 |        3 |           1 |
| 111 | baristaboy24         |        1 |              0 |        1 |        0 |          1 |        1 |           1 |
| 112 | bathtub_not_beach    |        1 |              0 |        1 |        0 |          1 |        1 |           1 |
| 113 | Fast-Engineer915     |        1 |              0 |        1 |        0 |          1 |        1 |           1 |
| 114 | Zakedawn             |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 115 | buddyomg             |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 116 | Wafflz__             |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 117 | BevvyTime            |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 118 | galaxygalaxy777      |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 119 | Squm9                |        1 |              0 |        1 |        0 |          1 |        1 |           1 |
| 120 | Captain_Obvious_x    |        1 |              0 |        1 |        0 |          1 |        1 |           1 |
| 121 | Fatty4forks          |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 122 | wostmardin           |        1 |              0 |        1 |        0 |          1 |        3 |           1 |
| 123 | Tspecs05             |        1 |              0 |        1 |        0 |          1 |        6 |           1 |
| 124 | exhaleair            |        1 |              0 |        1 |        0 |          1 |        3 |           1 |
| 125 | kempston_joystick    |        1 |              0 |        1 |        0 |          1 |        2 |           1 |
| 126 | rabbitradar          |        1 |              0 |        1 |        0 |          1 |        2 |           1 |
| 127 | TouristDramatic8295  |        1 |              0 |        1 |        0 |          1 |        1 |           1 |
| 128 | kevmccartney         |        1 |              0 |        1 |        0 |          1 |        1 |           1 |
| 129 | SoggyMattress2       |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 130 | boondocksaint08      |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 131 | OpScreechingHalt     |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 132 | Financial-Glass5693  |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 133 | Educational_Ad288    |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 134 | No_Amphibian6382     |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 135 | ThermoWizz           |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 136 | GuyInWessex          |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 137 | Likunandi            |        1 |              0 |        1 |        0 |          1 |        0 |           1 |
| 138 | Salt-Cup-2300        |        1 |              0 |        0 |        0 |          1 |        3 |           1 |
| 139 | Blackgotham-12       |        1 |              0 |        0 |        0 |          1 |        2 |           1 |
| 140 | Toast_for_President  |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
| 141 | jeromereyes          |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
| 142 | asdaf22              |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
| 143 | Adziboy              |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
| 144 | Henghast             |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
| 145 | oldredstang66        |        1 |              0 |        0 |        0 |          1 |        5 |           1 |
| 146 | rghsfc               |        1 |              0 |        0 |        0 |          1 |        4 |           1 |
| 147 | Weirdo_boy02         |        1 |              0 |        0 |        0 |          1 |        3 |           1 |
| 148 | fluffyplayery        |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
| 149 | Ahegaopizza          |        1 |              0 |        0 |        0 |          1 |        2 |           1 |
| 150 | PhilipRobertson      |        1 |              0 |        0 |        0 |          1 |        2 |           1 |
| 151 | thisisclassicus      |        1 |              0 |        0 |        0 |          1 |        2 |           1 |
| 152 | GuteLord-            |        1 |              0 |        0 |        0 |          1 |        2 |           1 |
| 153 | BanjoPants74         |        1 |              0 |        0 |        0 |          1 |        1 |           1 |
| 154 | J_Dymond             |        1 |              0 |        0 |        0 |          1 |        3 |           1 |
| 155 | madshjort            |        1 |              0 |        0 |        0 |          1 |        3 |           1 |
| 156 | allbarneynorubble    |        1 |              0 |        0 |        0 |          1 |        3 |           1 |
| 157 | LordOrtus            |        1 |              0 |        0 |        0 |          1 |        3 |           1 |