Schema

 - Matches:
     - MatchId: int
         - MatchWeek: int
         - HomeTeam: int
         - AwayTeam: int
         - MatchResult: pt.MatchResult
         - ThreadUrl: str
         - MatchTime: datetime (convert to UTC?)

 - Standings:
     - MatchId: int
         - UserName: str
             - Points: int

 - Predictions:
     - MatchId: int
         - UserName: str
             - Comment: str
             - CommentTime: datetime (convert to UTC?)

{
    "MatchId": {
        "0": {
            "MatchWeek": 0,
            "HomeTeam": "Southampton",
            "
        }
    }
}

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from pathlib import Path
import pandas as pd
from icecream import ic
import pendulum
import datetime

import predthread as pt
from predthread import fbref

In [3]:
root = Path(".").absolute()
print(root)

/Users/julianirwin/Projects/predthread/examples/southamton_24-25_33c895d4

In [4]:
club_names = pt.club_names(root)
api_keys = pt.api_keys(root)
match_metadata = pt.match_metadata(root, match_id=0)
matches_metadata = pt.matches_metadata(root)
matches_metadata_df = pt.matches_metadata_df(root)

# ic(club_names)
# ic(match_metadata)
# ic(matches_metadata)
pass

In [5]:
reddit = pt.open_reddit(**api_keys)

In [6]:
url = "https://www.reddit.com/r/SaintsFC/comments/19a1wtq/prediction_thread_week_28_swansea_city_southampton/"
thread = pt.open_thread(reddit, url)

In [7]:
ic(fbref.match_metadata(1))
pass

ic| fbref.match_metadata(1): {'AwayClub': 'Southampton',
                              'AwayGoals': '',
                              'HomeClub': 'Newcastle Utd',
                              'HomeGoals': '',
                              'MatchTimeUtc': '2024-08-17T15:00:00Z',
                              'MatchWeek': 1,
                              'ThreadUrl': ''}

In [32]:
# pt.append_match_metadata(root, fbref.match_metadata(4))

ValueError: Match metadata for MatchWeek 4 already exists

In [17]:
dt = datetime.datetime(2024, 1, 20, 6, 30)
predictions = pt.get_predictions(thread, comment_localtime_cutoff=dt)
predictions

,Comment,PredictedHomeGoals,PredictedAwayGoals
UserName,,,
meteoritee,2-2 continuing my run of guessing a draw so sa...,2,2
Hagranm,0-2 saints get a 30th minute goal then score a...,0,2
Kindlydestroyed1,3-2 saints,3,2
someonehasmygamertag,My two uni cities going at it - I’ll be in the...,3,0
Zou-KaiLi,1-3,1,3
...,...,...,...
infestationE15,1-1,1,1
hAkonf,1-5,1,5
ThatMoodyBstard,0-2,0,2
Hefty-Competition297,1-3 COYR,1,3
496e636f676e69746f,0-3,0,3

In [18]:
predictions.to_csv(root / "predictions" / "week-0.csv")

In [15]:
pd.read_csv(root / "predictions" / "week-0.csv").to_csv(root / "predictions" / "week-0b.csv")

In [11]:
pt.standings_after_df(root, 0)

      UserName  Points  PointsGained  Streak  Exacts  Corrects  Incorrects
0     gradi3nt       0             0       0       0         0           0
1    fake_user       1             1       1       0         1           0
2  theChamp420       3             3       1       1         0           0

In [42]:
pt.get_standings(thread)

                     Points  PointsGained  Exacts  Corrects  Wrongs
jrdn1616                 23             1       4        11      10
MetaRift                 23             1       2        17       7
HandsomedanNZ            21             1       3        12       7
ThatMoodyBstard          21             1       3        12      11
redditbanana42           21             1       2        15       9
...                     ...           ...     ...       ...     ...
Dmartinez8491             0             0       0         0       1
BlueInq                   0             0       0         0       1
Emergency-Room-5484       0             0       0         0       1
Extension-Tooth-163       0             0       0         0       1
mileskerowhack            0             0       0         0       1

[177 rows x 5 columns]