Schema

 - Matches:
     - MatchId: int
         - MatchWeek: int
         - HomeTeam: int
         - AwayTeam: int
         - MatchResult: pt.MatchResult
         - ThreadUrl: str
         - MatchTime: datetime (convert to UTC?)

 - Standings:
     - MatchId: int
         - UserName: str
             - Points: int

 - Predictions:
     - MatchId: int
         - UserName: str
             - Comment: str
             - CommentTime: datetime (convert to UTC?)


What if someone posts two comments?

{
    "MatchId": {
        "0": {
            "MatchWeek": 0,
            "HomeTeam": "Southampton",
            "
        }
    }
}

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from pathlib import Path
import pandas as pd
from icecream import ic

import predthread as pt
from predthread import fbref

from collections import defaultdict
from copy import deepcopy

In [3]:
root = Path(".").absolute()
print(root)

/Users/julianirwin/Projects/predthread/examples/southamton_24-25_33c895d4

In [4]:
club_names = pt.club_names(root)
api_keys = pt.api_keys(root)
match_metadata = pt.match_metadata(root, match_id=0)
matches_metadata = pt.matches_metadata(root)
matches_metadata_df = pt.matches_metadata_df(root)

# ic(club_names)
# ic(match_metadata)
# ic(matches_metadata)

In [5]:
match_id = 1

In [6]:
ic(fbref.match_metadata(1))
pass

ic| fbref.match_metadata(1): {'AwayClub': 'Southampton',
                              'AwayGoals': '',
                              'HomeClub': 'Newcastle Utd',
                              'HomeGoals': '',
                              'MatchTimeUtc': '2024-08-17T15:00:00Z',
                              'MatchWeek': 1,
                              'ThreadUrl': ''}

In [7]:
# pt.append_match_metadata(root, fbref.match_metadata(4))

In [8]:
pd.set_option("display.max_rows", None)
ps = pt.download_predictions(root, match_id)
ps.sort_values(["PredictedHomeGoals", "PredictedAwayGoals"], ascending=False)
# ps

,Comment,PredictedHomeGoals,PredictedAwayGoals
UserName,,,
Antidote-Killer,9-1,9,1
brandonouthouse,9-0 battering,9,0
BlueInq,6-0,6,0
Relevant_Rev,5-2 Saints,5,2
gubbyno,4-3. Revenge for last year,4,3
MonarchyBoner,4-2 Saints,4,2
BJH19,4-1,4,1
Weirdo_boy02,4-0,4,0
Whenthebeatdropolis,3 - 2,3,2
sgm94,3-2 saints adarma hat trick,3,2
guillotine-jones,3-2,3,2
Holy_Shit_Balls_69,3-2\n\nWe are legendary.,3,2
TheEggMan45,3-1. With Saints scoring all 3 in the first ha...,3,1
street--donut,3-1,3,1
MAFIAxMaverick,3-1,3,1
Cervix-Pounder,3 - 1,3,1
gedly89,3-1 Saints to dominate with a late goal conceded.,3,1
malkusm,3-1,3,1
Cormac419,3-1 saints\n\nFeeling good about this one but ...,3,1
zoinks10,3-1 Saints,3,1
saint-86,3-1,3,1
redditbanana42,3-1 still can't keep a clean sheet!,3,1
3rd__i,3-1 saints (Murillo red due to BBD shithousing),3,1
saintstu,3-1. Come on you Saints!,3,1
dan_3,3-1,3,1
master_shifwho,3-0. We show the Prem that we aren’t pushovers!,3,0
Adziboy,3-0,3,0
specifylength,3-0,3,0
FitzRoyced,3-0,3,0
whowantstogo,3-0,3,0
Hefty-Competition297,3-0 COYR,3,0
Anglo-fornian,3-0 saints win! Adarma starts replicating his ...,3,0
strider_tom,3-0,3,0
jjbc56,2-2 with a frustrating late equaliser from Forest,2,2
MetaRift,2-2,2,2
Zapdosman,2-2,2,2
Glittering-Cow-4702,2-2,2,2
baristaboy24,2-2,2,2
Bruceplanet,2-2 scrappy affair,2,2
LegitimatePass6924,2-2 for me,2,2
mcsgwigga,2-2,2,2
PhilipRobertson,2-2,2,2
West_Equivalent7997,2-2 Keeper mistake last 10min,2,2
madshjort,2-2,2,2
nape27,2-2,2,2
kyleandrew_7,2-2,2,2
gongasf,Saints 2-1 Forest,2,1
bundy554,Must win this game - 2-1,2,1
teuridge,2-1,2,1
gooffking,2-1,2,1
CelaenaSardothien007,2-1,2,1
MangerDanger1,2-1,2,1
Henghast,2-1,2,1
Hot_Chair_7523,2-1,2,1
delegod1,2-1,2,1
Jpwf,2-1 Saints,2,1
accidentalsalmon,2-1 us,2,1
Positive-Sound-4972,2 -1 with the most nervous last 10 minutes ever,2,1
Lost_Disk,2-1,2,1
Potato271,2-1,2,1
oldredstang66,2-1 because why not,2,1
fluffyplayery,Southampton 2 - 1 Forest,2,1
wostmardin,2-1,2,1
exhaleair,"2 - 1 , BBD, and KWP with the goals.",2,1
kempston_joystick,2-1 Saints,2,1
Tough-Whereas1205,2-1,2,1
jeromereyes,2-1,2,1
Intermittent-Thinker,2 - 1,2,1
LovingCatholicPriest,2-1,2,1
fartarus,2-1,2,1
Nixstricks,2-1 COYR,2,1
Ahegaopizza,2-1 oh gosh please we look good just make it h...,2,1
aredditusername69,2-1 Saints,2,1
MrRyan1320,2-1,2,1
HandsomedanNZ,2-1\n\nI’m conflicted because I’m a lifelong S...,2,1
mdubyo,2-1\n\nAdarma & BBD open their PL accounts.,2,1
King_Lamb,2-1 to Saints,2,1
tugboet,2-1. We are up 2-0 and give up a goal in the 8...,2,1
Toast_for_President,2-1 think we will dominate but a mistake at th...,2,1
chebalebs,"2-1, fuck it",2,1
LordOrtus,2-1,2,1
weatherghost,"2-1 Saints. After Newcastle, I'm optimistic fo...",2,1
Nervous_Jaguar_2826,"2 - 1, saints control the game, go 1-0 up in t...",2,1
shontgomery,2-1,2,1
Blackgotham-12,2-1 Brereton Diaz first goal,2,1
throwaway1throwawa,2-1 Saints win,2,1
SomeGuyCalledPercy,2-1 expecting another McCarthy shocker but I'm...,2,1
asdaf22,2 - 1 saints ez,2,1
darave123,2-0. Great team performance!,2,0
benscott81,2-0,2,0
Tspecs05,2-0. Saints,2,0
Desperate_Low9482,2-0,2,0
3ch03d,2-0,2,0
496e636f676e69746f,2-0,2,0
DrShaftmanPhD,2-0!,2,0
Tutush,2-0,2,0
soverign_cheese,2-0 saints,2,0
rghsfc,2-0 saints,2,0
BigTettenator,2-0,2,0
J_Dymond,2-0 saints,2,0
whattodotodo8,2-0 Saints win!,2,0
Dr-Honks,2-0,2,0
flailingpariah,1-3 My strategy is unrelenting pessimism and a...,1,3
Zstupple,1-3,1,3
UtterlyRedditculous,1-3,1,3
gradi3nt,1 - 2,1,2
NorwegianSaint,1-2,1,2
meteoritee,1-2,1,2
Kindlydestroyed,1-2 forest. A late mistake to undo the hard wo...,1,2
ThatMoodyBstard,1-2. Chris Wood brace is inevitable,1,2
JAChambel,1-2\nMy strategy will be to predict that we lo...,1,2
FalafelHalloumi,1-2,1,2
NagromNitsuj,Can’t quite predict a win yet. \n\n1-1,1,1
pctomfor,1 - 1. Saints score first. Still finding our f...,1,1
who905,1-1,1,1
Revolutionary_Cup602,1 - 1,1,1
pishkabob,"1-1 Finally bury one of our many chances, but ...",1,1
Saint_Noog,1-1 Early goal for Saints but late heartbreak,1,1
fcf4,1-1,1,1
JimmyRiddle707,1-1,1,1
lemezier,1-1,1,1
Zou-KaiLi,1-1,1,1
infestationE15,1-1,1,1
Bayne7096,A frustrating 1-1 draw,1,1
PunnyIsNotFunny,1-1 BBD to open the scoring,1,1
Nas1729,1-1,1,1
thatcrazyhorse,1-0,1,0
Salt-Cup-2300,1-0,1,0
jrdn1616,1-0. Adarma pen after berenton Diaz is fouled.,1,0
Potential-Oil-1795,1.0,1,0
magneticacorn,1-0,1,0
Many_Background_3679,1-0,1,0
MrJoshua_182,1 - 0,1,0
jayforplay,1-0,1,0
uuuuuuuhhhhh,1-0,1,0
Lucky_Strike1,1-0,1,0
allbarneynorubble,1-0,1,0
Weary_Initiative5582,1-0,1,0
thinlike_napkins,0-3 \n\nCan we please score,0,3
TheFuzzyEucalyptus,0-2,0,2
jackodriscol,0-2,0,2
Emergency-Room-5484,0-2,0,2
BlameTibor,0-2 I hope I'm wrong,0,2
PM_ME_YOUR_MARS_BARS,0-1. Brereton Diaz becomes Chilelé,0,1
slugmaniac,0-1,0,1
halarhala,0-1,0,1
Alina2017,0-0,0,0

In [9]:
pt.summarize_predictions(root, match_id)

{'TotalPredictions': 147,
 'TotalHomeWinPredictions': 101,
 'TotalAwayWinPredictions': 18,
 'TotalDrawPredictions': 28}

In [10]:
ps.loc["SomeGuyCalledPercy"]

Comment               2-1 expecting another McCarthy shocker but I'm...
PredictedHomeGoals                                                    2
PredictedAwayGoals                                                    1
Name: SomeGuyCalledPercy, dtype: object

In [11]:
new_standings = pt.calculate_updated_standings_after(root, match_id-1)
new_standings

,Points,PointsGained,Streak,Exacts,Corrects,Wrongs,MaxStreak
UserName,,,,,,,
Nixstricks,3,3,3,1,0,0,3
Jpwf,3,3,3,1,0,0,3
shontgomery,3,3,3,1,0,0,3
SomeGuyCalledPercy,3,3,3,1,0,0,3
jjbc56,1,1,1,0,1,0,1
gradi3nt,1,1,1,0,1,0,1
flailingpariah,1,1,1,0,1,0,1
Tutush,1,1,1,0,1,0,1
Salt-Cup-2300,1,1,1,0,1,0,1
delegod1,1,1,1,0,1,0,1
HandsomedanNZ,1,1,1,0,1,0,1
thisisclassicus,1,1,1,0,1,0,1
igsey,1,1,1,0,1,0,1
jackodriscol,1,1,1,0,1,0,1
Many_Background_3679,1,1,1,0,1,0,1
thatcrazyhorse,1,1,1,0,1,0,1
Emergency-Room-5484,1,1,1,0,1,0,1
Zstupple,1,1,1,0,1,0,1
mcsgwigga,1,1,1,0,1,0,1
Cervix-Pounder,1,1,1,0,1,0,1
Zapdosman,1,1,1,0,1,0,1
Positive-Sound-4972,1,1,1,0,1,0,1
teuridge,1,1,1,0,1,0,1
MangerDanger1,1,1,1,0,1,0,1
Blackgotham-12,1,1,1,0,1,0,1
FluidSaint,1,1,1,0,1,0,1
uuuuuuuhhhhh,1,1,1,0,1,0,1
Toast_for_President,1,1,1,0,1,0,1
NagromNitsuj,1,1,1,0,1,0,1
specifylength,1,1,1,0,1,0,1
saintstu,1,1,1,0,1,0,1
bendezhashein,1,1,1,0,1,0,1
LegitimatePass6924,1,1,1,0,1,0,1
infestationE15,1,1,1,0,1,0,1
Saint_Noog,1,1,1,0,1,0,1
fcf4,1,1,1,0,1,0,1
ThatMoodyBstard,1,1,1,0,1,0,1
benscott81,1,1,1,0,1,0,1
jeromereyes,1,1,1,0,1,0,1
chebalebs,1,1,1,0,1,0,1
asdaf22,1,1,1,0,1,0,1
T_Hr0,1,1,1,0,1,0,1
Potato271,1,1,1,0,1,0,1
Zou-KaiLi,1,1,1,0,1,0,1
Tough-Whereas1205,1,1,1,0,1,0,1
Adziboy,1,1,1,0,1,0,1
slugmaniac,1,1,1,0,1,0,1
fartarus,1,1,1,0,1,0,1
Henghast,1,1,1,0,1,0,1
oldredstang66,1,1,1,0,1,0,1
lemezier,1,1,1,0,1,0,1
PM_ME_YOUR_MARS_BARS,1,1,1,0,1,0,1
Revolutionary_Cup602,1,1,1,0,1,0,1
magneticacorn,1,1,1,0,1,0,1
jayforplay,1,1,1,0,1,0,1
FalafelHalloumi,1,1,1,0,1,0,1
rghsfc,1,1,1,0,1,0,1
TheFuzzyEucalyptus,1,1,1,0,1,0,1
Weirdo_boy02,1,1,1,0,1,0,1
Finoptics,1,1,1,0,1,0,1
Desperate_Low9482,1,1,1,0,1,0,1
halarhala,1,1,1,0,1,0,1
UtterlyRedditculous,1,1,1,0,1,0,1
brandonouthouse,1,1,1,0,1,0,1
JAChambel,1,1,1,0,1,0,1
fluffyplayery,1,1,1,0,1,0,1
Lucky_Strike1,1,1,1,0,1,0,1
FitzRoyced,1,1,1,0,1,0,1
mdubyo,1,1,1,0,1,0,1
kyleandrew_7,1,1,1,0,1,0,1
mr_grission,1,1,1,0,1,0,1
nape27,1,1,1,0,1,0,1
saint-86,1,1,1,0,1,0,1
malkusm,1,1,1,0,1,0,1
KingHarpoon616,1,1,1,0,1,0,1
hAkonf,1,1,1,0,1,0,1
Ahegaopizza,1,1,1,0,1,0,1
Nas1729,1,1,1,0,1,0,1
Intermittent-Thinker,1,1,1,0,1,0,1
pishkabob,1,1,1,0,1,0,1
MrJoshua_182,1,1,1,0,1,0,1
CelaenaSardothien007,1,1,1,0,1,0,1
chesterchugger,1,1,1,0,1,0,1
GuteLord-,1,1,1,0,1,0,1
PhilipRobertson,1,1,1,0,1,0,1
MetaRift,1,1,1,0,1,0,1
JimmyRiddle707,1,1,1,0,1,0,1
BanjoPants74,1,1,1,0,1,0,1
alki07,0,0,0,0,0,1,0
Antidote-Killer,0,0,0,0,0,1,0
wostmardin,0,0,0,0,0,1,0
MAFIAxMaverick,0,0,0,0,0,1,0
gooffking,0,0,0,0,0,1,0
Relevant_Rev,0,0,0,0,0,1,0
spankeycakes,0,0,0,0,0,1,0
Bruceplanet,0,0,0,0,0,1,0
roberthart327,0,0,0,0,0,1,0
darave123,0,0,0,0,0,1,0
Unlucky_Island_742,0,0,0,0,0,1,0
redditbanana42,0,0,0,0,0,1,0
Vsovs,0,0,0,0,0,1,0
WaltertheWobot,0,0,0,0,0,1,0
dan_3,0,0,0,0,0,1,0
happysnappygoat,0,0,0,0,0,1,0
whowantstogo,0,0,0,0,0,1,0
frooberts,0,0,0,0,0,1,0
gedly89,0,0,0,0,0,1,0
K3GGY,0,0,0,0,0,1,0
Dr-Honks,0,0,0,0,0,1,0
EntersMikers,0,0,0,0,0,1,0
Hefty-Competition297,0,0,0,0,0,1,0
Patentlyy,0,0,0,0,0,1,0
MrRyan1320,0,0,0,0,0,1,0
strider_tom,0,0,0,0,0,1,0
sgm94,0,0,0,0,0,1,0
J_Dymond,0,0,0,0,0,1,0
Tspecs05,0,0,0,0,0,1,0
guillotine-jones,0,0,0,0,0,1,0
Super-saints12,0,0,0,0,0,1,0
3rd__i,0,0,0,0,0,1,0
Hot_Chair_7523,0,0,0,0,0,1,0
master_shifwho,0,0,0,0,0,1,0
GrandmasterYoda1,0,0,0,0,0,1,0
whattodotodo8,0,0,0,0,0,1,0
Anglo-fornian,0,0,0,0,0,1,0

In [12]:
print(new_standings.reset_index().to_markdown())

|     | UserName             |   Points |   PointsGained |   Streak |   Exacts |   Corrects |   Wrongs |   MaxStreak |
|----:|:---------------------|---------:|---------------:|---------:|---------:|-----------:|---------:|------------:|
|   0 | Nixstricks           |        3 |              3 |        3 |        1 |          0 |        0 |           3 |
|   1 | Jpwf                 |        3 |              3 |        3 |        1 |          0 |        0 |           3 |
|   2 | shontgomery          |        3 |              3 |        3 |        1 |          0 |        0 |           3 |
|   3 | SomeGuyCalledPercy   |        3 |              3 |        3 |        1 |          0 |        0 |           3 |
|   4 | jjbc56               |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|   5 | gradi3nt             |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|   6 | flailingpariah       |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|   7 | Tutush               |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|   8 | Salt-Cup-2300        |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|   9 | delegod1             |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  10 | HandsomedanNZ        |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  11 | thisisclassicus      |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  12 | igsey                |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  13 | jackodriscol         |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  14 | Many_Background_3679 |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  15 | thatcrazyhorse       |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  16 | Emergency-Room-5484  |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  17 | Zstupple             |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  18 | mcsgwigga            |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  19 | Cervix-Pounder       |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  20 | Zapdosman            |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  21 | Positive-Sound-4972  |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  22 | teuridge             |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  23 | MangerDanger1        |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  24 | Blackgotham-12       |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  25 | FluidSaint           |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  26 | uuuuuuuhhhhh         |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  27 | Toast_for_President  |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  28 | NagromNitsuj         |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  29 | specifylength        |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  30 | saintstu             |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  31 | bendezhashein        |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  32 | LegitimatePass6924   |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  33 | infestationE15       |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  34 | Saint_Noog           |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  35 | fcf4                 |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  36 | ThatMoodyBstard      |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  37 | benscott81           |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  38 | jeromereyes          |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  39 | chebalebs            |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  40 | asdaf22              |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  41 | T_Hr0                |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  42 | Potato271            |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  43 | Zou-KaiLi            |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  44 | Tough-Whereas1205    |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  45 | Adziboy              |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  46 | slugmaniac           |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  47 | fartarus             |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  48 | Henghast             |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  49 | oldredstang66        |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  50 | lemezier             |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  51 | PM_ME_YOUR_MARS_BARS |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  52 | Revolutionary_Cup602 |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  53 | magneticacorn        |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  54 | jayforplay           |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  55 | FalafelHalloumi      |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  56 | rghsfc               |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  57 | TheFuzzyEucalyptus   |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  58 | Weirdo_boy02         |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  59 | Finoptics            |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  60 | Desperate_Low9482    |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  61 | halarhala            |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  62 | UtterlyRedditculous  |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  63 | brandonouthouse      |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  64 | JAChambel            |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  65 | fluffyplayery        |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  66 | Lucky_Strike1        |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  67 | FitzRoyced           |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  68 | mdubyo               |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  69 | kyleandrew_7         |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  70 | mr_grission          |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  71 | nape27               |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  72 | saint-86             |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  73 | malkusm              |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  74 | KingHarpoon616       |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  75 | hAkonf               |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  76 | Ahegaopizza          |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  77 | Nas1729              |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  78 | Intermittent-Thinker |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  79 | pishkabob            |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  80 | MrJoshua_182         |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  81 | CelaenaSardothien007 |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  82 | chesterchugger       |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  83 | GuteLord-            |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  84 | PhilipRobertson      |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  85 | MetaRift             |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  86 | JimmyRiddle707       |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  87 | BanjoPants74         |        1 |              1 |        1 |        0 |          1 |        0 |           1 |
|  88 | alki07               |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
|  89 | Antidote-Killer      |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
|  90 | wostmardin           |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
|  91 | MAFIAxMaverick       |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
|  92 | gooffking            |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
|  93 | Relevant_Rev         |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
|  94 | spankeycakes         |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
|  95 | Bruceplanet          |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
|  96 | roberthart327        |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
|  97 | darave123            |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
|  98 | Unlucky_Island_742   |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
|  99 | redditbanana42       |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 100 | Vsovs                |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 101 | WaltertheWobot       |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 102 | dan_3                |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 103 | happysnappygoat      |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 104 | whowantstogo         |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 105 | frooberts            |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 106 | gedly89              |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 107 | K3GGY                |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 108 | Dr-Honks             |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 109 | EntersMikers         |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 110 | Hefty-Competition297 |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 111 | Patentlyy            |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 112 | MrRyan1320           |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 113 | strider_tom          |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 114 | sgm94                |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 115 | J_Dymond             |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 116 | Tspecs05             |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 117 | guillotine-jones     |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 118 | Super-saints12       |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 119 | 3rd__i               |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 120 | Hot_Chair_7523       |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 121 | master_shifwho       |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 122 | GrandmasterYoda1     |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 123 | whattodotodo8        |        0 |              0 |        0 |        0 |          0 |        1 |           0 |
| 124 | Anglo-fornian        |        0 |              0 |        0 |        0 |          0 |        1 |           0 |

In [13]:
predictions = pt.load_predictions(root, match_id)
old_standings = pt.load_standings_after(root, match_id - 1)
new_standings_p = pt.load_standings_after(root, match_id)
new_standings_p = new_standings.rename(columns=lambda x: x + "*")
predictions.join(old_standings, new_standings_p)

KeyError:                       Points*  PointsGained*  Streak*  Exacts*  Corrects*  \
UserName
Nixstricks                  3              3        3        1          0
Jpwf                        3              3        3        1          0
shontgomery                 3              3        3        1          0
SomeGuyCalledPercy          3              3        3        1          0
jjbc56                      1              1        1        0          1
gradi3nt                    1              1        1        0          1
flailingpariah              1              1        1        0          1
Tutush                      1              1        1        0          1
Salt-Cup-2300               1              1        1        0          1
delegod1                    1              1        1        0          1
HandsomedanNZ               1              1        1        0          1
thisisclassicus             1              1        1        0          1
igsey                       1              1        1        0          1
jackodriscol                1              1        1        0          1
Many_Background_3679        1              1        1        0          1
thatcrazyhorse              1              1        1        0          1
Emergency-Room-5484         1              1        1        0          1
Zstupple                    1              1        1        0          1
mcsgwigga                   1              1        1        0          1
Cervix-Pounder              1              1        1        0          1
Zapdosman                   1              1        1        0          1
Positive-Sound-4972         1              1        1        0          1
teuridge                    1              1        1        0          1
MangerDanger1               1              1        1        0          1
Blackgotham-12              1              1        1        0          1
FluidSaint                  1              1        1        0          1
uuuuuuuhhhhh                1              1        1        0          1
Toast_for_President         1              1        1        0          1
NagromNitsuj                1              1        1        0          1
specifylength               1              1        1        0          1
saintstu                    1              1        1        0          1
bendezhashein               1              1        1        0          1
LegitimatePass6924          1              1        1        0          1
infestationE15              1              1        1        0          1
Saint_Noog                  1              1        1        0          1
fcf4                        1              1        1        0          1
ThatMoodyBstard             1              1        1        0          1
benscott81                  1              1        1        0          1
jeromereyes                 1              1        1        0          1
chebalebs                   1              1        1        0          1
asdaf22                     1              1        1        0          1
T_Hr0                       1              1        1        0          1
Potato271                   1              1        1        0          1
Zou-KaiLi                   1              1        1        0          1
Tough-Whereas1205           1              1        1        0          1
Adziboy                     1              1        1        0          1
slugmaniac                  1              1        1        0          1
fartarus                    1              1        1        0          1
Henghast                    1              1        1        0          1
oldredstang66               1              1        1        0          1
lemezier                    1              1        1        0          1
PM_ME_YOUR_MARS_BARS        1              1        1        0          1
Revolutionary_Cup602        1              1        1        0          1
magneticacorn               1              1        1        0          1
jayforplay                  1              1        1        0          1
FalafelHalloumi             1              1        1        0          1
rghsfc                      1              1        1        0          1
TheFuzzyEucalyptus          1              1        1        0          1
Weirdo_boy02                1              1        1        0          1
Finoptics                   1              1        1        0          1
Desperate_Low9482           1              1        1        0          1
halarhala                   1              1        1        0          1
UtterlyRedditculous         1              1        1        0          1
brandonouthouse             1              1        1        0          1
JAChambel                   1              1        1        0          1
fluffyplayery               1              1        1        0          1
Lucky_Strike1               1              1        1        0          1
FitzRoyced                  1              1        1        0          1
mdubyo                      1              1        1        0          1
kyleandrew_7                1              1        1        0          1
mr_grission                 1              1        1        0          1
nape27                      1              1        1        0          1
saint-86                    1              1        1        0          1
malkusm                     1              1        1        0          1
KingHarpoon616              1              1        1        0          1
hAkonf                      1              1        1        0          1
Ahegaopizza                 1              1        1        0          1
Nas1729                     1              1        1        0          1
Intermittent-Thinker        1              1        1        0          1
pishkabob                   1              1        1        0          1
MrJoshua_182                1              1        1        0          1
CelaenaSardothien007        1              1        1        0          1
chesterchugger              1              1        1        0          1
GuteLord-                   1              1        1        0          1
PhilipRobertson             1              1        1        0          1
MetaRift                    1              1        1        0          1
JimmyRiddle707              1              1        1        0          1
BanjoPants74                1              1        1        0          1
alki07                      0              0        0        0          0
Antidote-Killer             0              0        0        0          0
wostmardin                  0              0        0        0          0
MAFIAxMaverick              0              0        0        0          0
gooffking                   0              0        0        0          0
Relevant_Rev                0              0        0        0          0
spankeycakes                0              0        0        0          0
Bruceplanet                 0              0        0        0          0
roberthart327               0              0        0        0          0
darave123                   0              0        0        0          0
Unlucky_Island_742          0              0        0        0          0
redditbanana42              0              0        0        0          0
Vsovs                       0              0        0        0          0
WaltertheWobot              0              0        0        0          0
dan_3                       0              0        0        0          0
happysnappygoat             0              0        0        0          0
whowantstogo                0              0        0        0          0
frooberts                   0              0        0        0          0
gedly89                     0              0        0        0          0
K3GGY                       0              0        0        0          0
Dr-Honks                    0              0        0        0          0
EntersMikers                0              0        0        0          0
Hefty-Competition297        0              0        0        0          0
Patentlyy                   0              0        0        0          0
MrRyan1320                  0              0        0        0          0
strider_tom                 0              0        0        0          0
sgm94                       0              0        0        0          0
J_Dymond                    0              0        0        0          0
Tspecs05                    0              0        0        0          0
guillotine-jones            0              0        0        0          0
Super-saints12              0              0        0        0          0
3rd__i                      0              0        0        0          0
Hot_Chair_7523              0              0        0        0          0
master_shifwho              0              0        0        0          0
GrandmasterYoda1            0              0        0        0          0
whattodotodo8               0              0        0        0          0
Anglo-fornian               0              0        0        0          0

                      Wrongs*  MaxStreak*
UserName
Nixstricks                  0           3
Jpwf                        0           3
shontgomery                 0           3
SomeGuyCalledPercy          0           3
jjbc56                      0           1
gradi3nt                    0           1
flailingpariah              0           1
Tutush                      0           1
Salt-Cup-2300               0           1
delegod1                    0           1
HandsomedanNZ               0           1
thisisclassicus             0           1
igsey                       0           1
jackodriscol                0           1
Many_Background_3679        0           1
thatcrazyhorse              0           1
Emergency-Room-5484         0           1
Zstupple                    0           1
mcsgwigga                   0           1
Cervix-Pounder              0           1
Zapdosman                   0           1
Positive-Sound-4972         0           1
teuridge                    0           1
MangerDanger1               0           1
Blackgotham-12              0           1
FluidSaint                  0           1
uuuuuuuhhhhh                0           1
Toast_for_President         0           1
NagromNitsuj                0           1
specifylength               0           1
saintstu                    0           1
bendezhashein               0           1
LegitimatePass6924          0           1
infestationE15              0           1
Saint_Noog                  0           1
fcf4                        0           1
ThatMoodyBstard             0           1
benscott81                  0           1
jeromereyes                 0           1
chebalebs                   0           1
asdaf22                     0           1
T_Hr0                       0           1
Potato271                   0           1
Zou-KaiLi                   0           1
Tough-Whereas1205           0           1
Adziboy                     0           1
slugmaniac                  0           1
fartarus                    0           1
Henghast                    0           1
oldredstang66               0           1
lemezier                    0           1
PM_ME_YOUR_MARS_BARS        0           1
Revolutionary_Cup602        0           1
magneticacorn               0           1
jayforplay                  0           1
FalafelHalloumi             0           1
rghsfc                      0           1
TheFuzzyEucalyptus          0           1
Weirdo_boy02                0           1
Finoptics                   0           1
Desperate_Low9482           0           1
halarhala                   0           1
UtterlyRedditculous         0           1
brandonouthouse             0           1
JAChambel                   0           1
fluffyplayery               0           1
Lucky_Strike1               0           1
FitzRoyced                  0           1
mdubyo                      0           1
kyleandrew_7                0           1
mr_grission                 0           1
nape27                      0           1
saint-86                    0           1
malkusm                     0           1
KingHarpoon616              0           1
hAkonf                      0           1
Ahegaopizza                 0           1
Nas1729                     0           1
Intermittent-Thinker        0           1
pishkabob                   0           1
MrJoshua_182                0           1
CelaenaSardothien007        0           1
chesterchugger              0           1
GuteLord-                   0           1
PhilipRobertson             0           1
MetaRift                    0           1
JimmyRiddle707              0           1
BanjoPants74                0           1
alki07                      1           0
Antidote-Killer             1           0
wostmardin                  1           0
MAFIAxMaverick              1           0
gooffking                   1           0
Relevant_Rev                1           0
spankeycakes                1           0
Bruceplanet                 1           0
roberthart327               1           0
darave123                   1           0
Unlucky_Island_742          1           0
redditbanana42              1           0
Vsovs                       1           0
WaltertheWobot              1           0
dan_3                       1           0
happysnappygoat             1           0
whowantstogo                1           0
frooberts                   1           0
gedly89                     1           0
K3GGY                       1           0
Dr-Honks                    1           0
EntersMikers                1           0
Hefty-Competition297        1           0
Patentlyy                   1           0
MrRyan1320                  1           0
strider_tom                 1           0
sgm94                       1           0
J_Dymond                    1           0
Tspecs05                    1           0
guillotine-jones            1           0
Super-saints12              1           0
3rd__i                      1           0
Hot_Chair_7523              1           0
master_shifwho              1           0
GrandmasterYoda1            1           0
whattodotodo8               1           0
Anglo-fornian               1           0

In [15]:
pt.summarize_standings_after(root, match_id)

{'TotalExacts': 3, 'TotalCorrects': 15}

# Post Template

In [ ]:
m_next = pt.match_metadata(root, match_id+1)
m_last = pt.match_metadata(root, match_id)

s_pred = pt.summarize_predictions(root, match_id - 1)
s_stand = pt.summarize_standings_after(root, match_id-1)

print(f"""
# Prediction Thread Match {match_id}: {m_next["HomeClub"]} vs {m_next["AwayClub"]}

# Home - Away Format

 - Home: {m_next["HomeClub"]}
 - Away: {m_next["AwayClub"]}

# Game Rules

 - Post a top level comment in this thread at least one hour before kickoff, before lineups are posted.
 - Follow the format of this example comment: "0 - 3. Banter goes here."
 - Comment format must be "[Home Score] - [Away Score]. [Optional explanation, detailed prediction, or general shit talking here.]"
 - Scoring:
    - **3 points** for an exactly correct prediction.
    - **1 points** for a correct result.
    - **0 points** for an incorrect result.
- DM me with any problems, questions, comments.

# Summary of Last Match ({m_last["HomeClub"]} - {m_last["AwayClub"]})

{m_last["ThreadUrl"]}

 - Total Predictions: {s_pred["TotalPredictions"]}
 - Predicted Home Wins: {s_pred["TotalHomeWinPredictions"]} 
 - Predicted Away Wins: {s_pred["TotalAwayWinPredictions"]} 
 - Predicted Draws: {s_pred["TotalDrawPredictions"]}
 - Exacts: {s_stand["TotalExacts"]}
 - Corrects: {s_stand["TotalCorrects"]} 

# Standings
{new_standings.reset_index().to_markdown()}
""")